/**
 * tamagui-tokens.mjs — pure, side-effect-free derivation of the Tamagui token/theme
 * data from the SAME `src/tokens/tokens.json` that `generate-theme.mjs` consumes.
 *
 * This module has NO filesystem or Tamagui-runtime dependencies so it can be imported
 * by BOTH the generator script (`generate-tamagui-config.mjs`) and the Layer-1
 * token-parity vitest (`src/__tests__/token-parity.test.ts`). The parity test proves,
 * by construction, that the values below resolve to the byte-identical CSS values the
 * browser gets from `theme.css` — so color/spacing/radius/font can never drift between
 * the Tailwind (`theme.css`) and Tamagui render targets. See
 * docs/react-native-tamagui-migration.md §3 (Layer 1) and §5.
 */

// ── Spectrum interpolation ──────────────────────────────────────────
// Byte-for-byte identical to generate-theme.mjs#buildSpectrum: anchors (brand-1..5) at
// indices 1,14,27,40,53 (spacing 13); linear RGB lerp between consecutive anchors, rounded.
// Kept in lockstep by the token-parity test, which compares this output to theme.css.
const hexToRgb = (h) => {
  const n = h.replace('#', '');
  return [0, 2, 4].map((i) => parseInt(n.slice(i, i + 2), 16));
};
const rgbToHex = (rgb) =>
  '#' + rgb.map((c) => Math.round(c).toString(16).padStart(2, '0')).join('');

export function buildSpectrum(spec, colorMap) {
  const anchorNames = ['brand-1', 'brand-2', 'brand-3', 'brand-4', 'brand-5'];
  const anchors = anchorNames.map((n) => hexToRgb(colorMap[n].light));
  const spacing = 13; // anchors at 1, 14, 27, 40, 53
  const out = [];
  for (let i = 1; i <= spec.steps; i++) {
    const pos = i - 1; // 0-based position along the ramp
    const seg = Math.min(Math.floor(pos / spacing), anchors.length - 2);
    const t = (pos - seg * spacing) / spacing;
    const a = anchors[seg];
    const b = anchors[seg + 1];
    const rgb = [0, 1, 2].map((c) => a[c] + (b[c] - a[c]) * t);
    out.push({ name: `spectrum-${i}`, value: rgbToHex(rgb) });
  }
  return out;
}

/**
 * Derive the full Tamagui token payload from a parsed tokens.json.
 *
 * Returns:
 *   - radius:  { 'radius-sm': '0.125rem', … }         (from tokens.theme, radius-* keys)
 *   - fonts:   { 'font-sans': 'TypeMates …', … }      (from tokens.theme, font-* keys)
 *   - themes.light: { <colorName>: <cssValue>, … }    (every authored color + spectrum, light)
 *   - themes.dark:  { <colorName>: <cssValue>, … }    (light ⊕ dark overrides — the FULLY
 *                                                      RESOLVED dark theme, exactly what the
 *                                                      browser computes under [data-theme="dark"])
 *
 * Values are the exact CSS strings from tokens.json so parity with theme.css is byte-identical.
 */
export function buildTamaguiTokens(tokens) {
  const colorMap = Object.fromEntries(tokens.colors.map((c) => [c.name, c]));
  const spectrum = buildSpectrum(tokens.spectrum, colorMap);

  // Full ordered color list: authored colors, then spectrum (same order as generate-theme.mjs).
  const colors = [
    ...tokens.colors.map((c) => ({ name: c.name, light: c.light, dark: c.dark })),
    ...spectrum.map((s) => ({ name: s.name, light: s.value, dark: s.value })),
  ];

  const radius = {};
  const fonts = {};
  for (const [k, v] of Object.entries(tokens.theme)) {
    if (k.startsWith('radius')) radius[k] = v;
    else if (k.startsWith('font')) fonts[k] = v;
  }

  const light = {};
  const dark = {};
  for (const c of colors) {
    light[c.name] = c.light;
    // Fully-resolved dark theme: a token with no distinct dark value inherits its light value,
    // exactly as the CSS cascade resolves it under [data-theme="dark"].
    dark[c.name] = c.dark;
  }

  return { radius, fonts, themes: { light, dark } };
}

/**
 * Render the checked-in generated module (`src/tamagui/tokens.generated.ts`).
 *
 * A pure-data TypeScript module — NO `@tamagui/core` import — so the token-parity vitest
 * (node env, no Tamagui installed) can import it directly. The buildable `tamagui.config.ts`
 * (Phase 1, needs @tamagui/core) is a thin shell that feeds this data into `createTamagui`.
 */
export function renderTokensModule(tokens) {
  const { radius, fonts, themes } = buildTamaguiTokens(tokens);
  const j = (obj) => JSON.stringify(obj, null, 2).replace(/\n/g, '\n');
  return `// AUTO-GENERATED by libs/css/scripts/generate-tamagui-config.mjs — DO NOT EDIT.
// Source of truth: src/tokens/tokens.json. Regenerate with:
//   pnpm --filter @lmthing/css generate
//
// Pure data (no @tamagui/core import) so the Layer-1 token-parity test can load it in a
// node env. Every value here is byte-identical to the corresponding CSS custom property in
// src/theme.css — proven by src/__tests__/token-parity.test.ts. See
// docs/react-native-tamagui-migration.md §5.

/** radius-* scale tokens (exact CSS values from tokens.json → tokens.theme). */
export const radius = ${j(radius)} as const;

/** font-* family tokens (exact CSS values). */
export const fonts = ${j(fonts)} as const;

/**
 * Theme colors keyed by design-token name. \`light\` mirrors :root; \`dark\` is the FULLY
 * RESOLVED [data-theme="dark"] theme (light ⊕ dark overrides), so a Tamagui theme can be
 * built directly from either map without replaying the CSS cascade.
 */
export const themes = {
  light: ${j(themes.light).replace(/\n/g, '\n  ')},
  dark: ${j(themes.dark).replace(/\n/g, '\n  ')},
} as const;

export type TokenColorName = keyof typeof themes.light;
export type ThemeName = keyof typeof themes;

export default { radius, fonts, themes };
`;
}
