/**
 * Prop bags for the former `@lmthing/css/components/functions/index.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.functions-editor__textarea` */
export const FUNCTIONS_EDITOR_TEXTAREA = {
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "0%",
  "minHeight": "20rem",
  "fontFamily": "var(--font-mono, monospace)",
  "fontSize": "0.8125rem",
  "resize": "vertical",
  "width": "100%"
} as const

