//! Where this shell points, and the object it tells the page about.
//!
//! The renderer cannot work any of this out for itself. It is served from
//! `tauri://localhost` (macOS/Linux) or `http://tauri.localhost` (Windows), so
//! `window.location` names neither the pod nor the gateway — every answer the web
//! build normally derives from the origin has to be supplied by the host.
//!
//! Phase 1 is cloud-only, so these are constants plus env overrides. Persisted,
//! user-editable settings arrive with local mode, which is the first thing that
//! genuinely needs to CHANGE them at runtime; adding a settings store before
//! anything can write to it would be a store with one hard-coded value in it.

use serde::{Deserialize, Serialize};

/// Must match `DESKTOP_PROTOCOL_VERSION` in `sdk/org/libs/auth/src/env.ts`.
///
/// The page ignores a bridge announcing any other value — wholesale, not
/// field-by-field — so a shell and a bundle that disagree degrade to "not
/// desktop" rather than to a half-understood object. Bump this only when a field
/// changes meaning or is removed.
const PROTOCOL_VERSION: u32 = 1;

const DEFAULT_API_BASE: &str = "https://lmthing.chat";
const DEFAULT_CLOUD_BASE: &str = "https://lmthing.cloud";
const DEFAULT_TEAM_BASE: &str = "https://lmthing.team";
const DEFAULT_COM_BASE: &str = "https://lmthing.com";

/// The DATA half of `window.__LMTHING_DESKTOP__`.
///
/// The behaviour half (`startSso`) is attached by the bundle itself, in
/// `src/desktop.ts` — that keeps the Tauri JS plugins inside this app instead of
/// leaking a desktop dependency into `@lmthing/auth`, which every other target
/// also imports.
#[derive(Serialize)]
#[serde(rename_all = "camelCase")]
pub struct DesktopBridge {
    pub protocol_version: u32,
    pub platform: &'static str,
    pub mode: &'static str,
    pub api_base: String,
    pub cloud_base: String,
    pub team_base: String,
    pub com_base: String,
}

impl DesktopBridge {
    /// Read the persisted local-mode setting, if any.
    ///
    /// Written by `commands::local_mode_enable` and read here at window creation, because the
    /// bridge is injected before any page script runs and `@lmthing/auth` reads it synchronously
    /// during module init — there is no later moment to change it in. Switching modes therefore
    /// restarts the window, which is also the honest behaviour: every socket and every cached
    /// session belongs to the pod being left behind.
    pub fn load_with(local_base: Option<String>) -> Self {
        let mut me = Self::load();
        if let Some(base) = local_base {
            me.mode = "local";
            me.api_base = base;
        }
        me
    }

    pub fn load() -> Self {
        Self {
            protocol_version: PROTOCOL_VERSION,
            platform: platform(),
            // Phase 1 is cloud-only. Local mode flips this to "local" and repoints
            // `api_base` at the loopback sidecar — which is precisely why the page
            // reads these at RUNTIME rather than being built against them.
            mode: "cloud",
            api_base: env_or("LMTHING_API_BASE", DEFAULT_API_BASE),
            cloud_base: env_or("LMTHING_CLOUD_BASE", DEFAULT_CLOUD_BASE),
            team_base: env_or("LMTHING_TEAM_BASE", DEFAULT_TEAM_BASE),
            com_base: env_or("LMTHING_COM_BASE", DEFAULT_COM_BASE),
        }
    }

    /// The script Tauri runs before ANY page script, on every navigation.
    ///
    /// `serde_json` does the escaping, so a value containing a quote or a `</script`
    /// cannot break out of the assignment.
    pub fn initialization_script(&self) -> String {
        let json =
            serde_json::to_string(self).expect("bridge is plain data and cannot fail to serialize");
        format!("window.__LMTHING_DESKTOP__ = {json};")
    }
}

/// Trimmed, and with any trailing slashes removed, so the page can always write
/// `${base}/api/...`. An empty or whitespace-only override falls back to the
/// default rather than producing a bridge that addresses nothing.
fn env_or(key: &str, fallback: &str) -> String {
    let value = std::env::var(key).unwrap_or_default();
    let trimmed = value.trim().trim_end_matches('/');
    if trimmed.is_empty() {
        fallback.to_string()
    } else {
        trimmed.to_string()
    }
}

/// The design-token colours the shell needs before any CSS exists.
///
/// Generated by `scripts/generate-tauri-conf.mjs` from `libs/css/src/tokens/tokens.json`, because a
/// hex literal must not appear in a committed file — the same rule `lint:tokens` enforces on `src/`,
/// applied by hand here since that linter does not read Rust. `include_str!` makes a stale generated
/// file a COMPILE error rather than a colour that quietly drifts from the design system.
#[derive(Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Tokens {
    pub background_light: String,
    pub background_dark: String,
}

impl Tokens {
    pub fn load() -> Self {
        serde_json::from_str(include_str!("../tokens.generated.json")).expect(
            "tokens.generated.json is generated and must parse; run `pnpm generate:tauri-conf`",
        )
    }

    /// The pre-paint window background for the OS theme in effect.
    ///
    /// Picking by theme is the whole point: painting the light colour under a dark system theme is
    /// a full-brightness flash on every launch, which is the seam this token exists to close.
    pub fn background_for(&self, dark: bool) -> &str {
        if dark {
            &self.background_dark
        } else {
            &self.background_light
        }
    }
}

fn platform() -> &'static str {
    if cfg!(target_os = "macos") {
        "macos"
    } else if cfg!(target_os = "windows") {
        "windows"
    } else {
        "linux"
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn strips_trailing_slashes_and_falls_back_on_blank() {
        // The page concatenates `${apiBase}/api/...`, so a trailing slash is a
        // double slash in every request the app makes.
        std::env::set_var("LMTHING_TEST_BASE", "https://example.test///");
        assert_eq!(
            env_or("LMTHING_TEST_BASE", "fallback"),
            "https://example.test"
        );

        std::env::set_var("LMTHING_TEST_BASE", "   ");
        assert_eq!(env_or("LMTHING_TEST_BASE", "fallback"), "fallback");

        std::env::remove_var("LMTHING_TEST_BASE");
        assert_eq!(env_or("LMTHING_TEST_BASE", "fallback"), "fallback");
    }

    #[test]
    fn generated_tokens_parse_and_the_two_themes_differ() {
        // `include_str!` already makes a missing file a compile error; this catches the subtler
        // case of a generator that ran but produced something unusable.
        let tokens = Tokens::load();
        assert!(tokens.background_light.starts_with('#'));
        assert!(tokens.background_dark.starts_with('#'));
        assert_ne!(
            tokens.background_light, tokens.background_dark,
            "one colour for both themes means the launch flash is back on one of them"
        );
        assert_eq!(tokens.background_for(true), tokens.background_dark);
        assert_eq!(tokens.background_for(false), tokens.background_light);
    }

    #[test]
    fn injection_script_announces_the_protocol_version_the_page_expects() {
        let script = DesktopBridge::load().initialization_script();
        assert!(script.starts_with("window.__LMTHING_DESKTOP__ = {"));
        assert!(script.contains("\"protocolVersion\":1"));
        // camelCase, because that is what `DesktopBridge` in libs/auth/src/env.ts reads.
        assert!(script.contains("\"apiBase\""));
        assert!(script.contains("\"cloudBase\""));
        assert!(script.contains("\"teamBase\""));
        // Without this the shell signs in against production no matter where it is pointed.
        assert!(script.contains("\"comBase\""));
    }
}
