/**
 * Prop bags for the former `@lmthing/css/components/workflow/step-card/index.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.step-card__drag-icon` */
export const STEP_CARD_DRAG_ICON = {
  "width": "$4",
  "height": "$4"
} as const

/** `.step-card__action-icon` */
export const STEP_CARD_ACTION_ICON = {
  "width": "$4",
  "height": "$4"
} as const

