/**
 * Prop bags for the former `@lmthing/css/components/workflow/step-schema-editor/index.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.schema-editor__empty-icon` */
export const SCHEMA_EDITOR_EMPTY_ICON = {
  "width": "$6",
  "height": "$6",
  "color": "var(--muted-foreground)"
} as const

/** `.schema-editor__empty-caption` */
export const SCHEMA_EDITOR_EMPTY_CAPTION = {
  "marginBottom": "1rem"
} as const

/** `.schema-editor__add-icon` */
export const SCHEMA_EDITOR_ADD_ICON = {
  "width": "$4",
  "height": "$4"
} as const

/** `.schema-editor__code-textarea` */
export const SCHEMA_EDITOR_CODE_TEXTAREA = {
  "fontFamily": "monospace",
  "minHeight": "15rem"
} as const

/** `.schema-editor__code-error` */
export const SCHEMA_EDITOR_CODE_ERROR = {
  "color": "var(--color-red-500)",
  "marginTop": "0.5rem"
} as const

/** `.property-row__move-icon` */
export const PROPERTY_ROW_MOVE_ICON = {
  "width": "$3.5",
  "height": "$3.5"
} as const

/** `.property-row__icon` */
export const PROPERTY_ROW_ICON = {
  "width": "$4",
  "height": "$4"
} as const

/** `.property-row__description-hint` */
export const PROPERTY_ROW_DESCRIPTION_HINT = {
  "maxWidth": "100px",
  "overflow": "hidden",
  "textOverflow": "ellipsis",
  "whiteSpace": "nowrap"
} as const

/** `.property-row__delete-icon` */
export const PROPERTY_ROW_DELETE_ICON = {
  "width": "$4",
  "height": "$4",
  "color": "var(--destructive)"
} as const

/** `.property-row__range-input` */
export const PROPERTY_ROW_RANGE_INPUT = {
  "width": "5rem"
} as const

/** `.property-row__description-input` */
export const PROPERTY_ROW_DESCRIPTION_INPUT = {
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "0%"
} as const

/** `.nested-properties__add-btn` */
export const NESTED_PROPERTIES_ADD_BTN = {
  "width": "100%"
} as const

/** `.nested-properties__add-icon` */
export const NESTED_PROPERTIES_ADD_ICON = {
  "width": "$4",
  "height": "$4"
} as const
