/**
 * Prop bags for the former `@lmthing/css/components/workflow/workflow-card/index.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.workflow-card__icon` */
export const WORKFLOW_CARD_ICON = {
  "width": "$4",
  "height": "$4"
} as const

/** `.workflow-card__check-icon` */
export const WORKFLOW_CARD_CHECK_ICON = {
  "width": "$3",
  "height": "$3",
  "color": "#fff" // ds-lint-ok: literal from a stock Tailwind color utility, theme-independent
} as const

