/**
 * Prop bags for the former `@lmthing/css/components/workflow/workflow-list/index.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.workflow-list__create-icon` */
export const WORKFLOW_LIST_CREATE_ICON = {
  "width": "$5",
  "height": "$5"
} as const

/** `.workflow-list__stats` */
export const WORKFLOW_LIST_STATS = {
  "display": "flex",
  "alignItems": "center",
  "marginBottom": "1.5rem"
} as const

/** `.workflow-list__stat-row` */
export const WORKFLOW_LIST_STAT_ROW = {
  "display": "flex",
  "alignItems": "center"
} as const

/** `.workflow-list__filters` */
export const WORKFLOW_LIST_FILTERS = {
  "display": "flex",
  "flexWrap": "wrap"
} as const

/** `.workflow-list__search-icon` */
export const WORKFLOW_LIST_SEARCH_ICON = {
  "position": "absolute",
  "width": "$5",
  "height": "$5",
  "left": "0.75rem",
  "top": "50%",
  "transform": "translateY(-50%)",
  "color": "var(--muted-foreground)"
} as const

/** `.workflow-list__search-input` */
export const WORKFLOW_LIST_SEARCH_INPUT = {
  "paddingLeft": "2.5rem"
} as const

/** `.workflow-list__view-icon` */
export const WORKFLOW_LIST_VIEW_ICON = {
  "width": "$4",
  "height": "$4"
} as const

/** `.workflow-list__empty-first-icon` */
export const WORKFLOW_LIST_EMPTY_FIRST_ICON = {
  "width": "$10",
  "height": "$10",
  "color": "#fff" // ds-lint-ok: literal from a stock Tailwind color utility, theme-independent
} as const

/** `.workflow-list__empty-first-caption` */
export const WORKFLOW_LIST_EMPTY_FIRST_CAPTION = {
  "marginBottom": "2rem",
  "maxWidth": "28rem",
  "marginInline": "auto"
} as const

