/**
 * Prop bags for the former `@lmthing/css/components/computer/ide-file-tree.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.ide-file-tree__icon` */
export const IDE_FILE_TREE_ICON = {
  "flexShrink": 0,
  "color": "$muted-foreground"
} as const

/** `.ide-file-tree__icon--folder` */
export const IDE_FILE_TREE_ICON_FOLDER = {
  "color": "$primary"
} as const

/** `.ide-file-tree__context-item` */
export const IDE_FILE_TREE_CONTEXT_ITEM = {
  "display": "flex",
  "alignItems": "center",
  "gap": "$2",
  "paddingHorizontal": "$2",
  "paddingVertical": "$1.5",
  "fontSize": "$sm",
  "cursor": "pointer",
  "hoverStyle": {
    "backgroundColor": "$accent"
  },
  "borderRadius": "$radius",
  "outlineWidth": 0,
  "outlineStyle": "none"
} as const

/** `.ide-file-tree__context-item--danger` */
export const IDE_FILE_TREE_CONTEXT_ITEM_DANGER = {
  "color": "$destructive"
} as const

/** `.ide-file-tree__dialog-title` */
export const IDE_FILE_TREE_DIALOG_TITLE = {
  "fontSize": "$lg",
  "fontWeight": "$semibold",
  "marginBottom": "$4"
} as const

/** `.ide-file-tree__dialog-input` */
export const IDE_FILE_TREE_DIALOG_INPUT = {
  "width": "100%",
  "paddingHorizontal": "$3",
  "paddingVertical": "$2",
  "backgroundColor": "$background",
  "borderRadius": "$radius",
  "borderWidth": 1,
  "borderColor": "$border",
  "focusStyle": {
    "borderColor": "$primary"
  },
  "outlineWidth": 0,
  "outlineStyle": "none",
  "fontSize": "$sm"
} as const

