/**
 * Prop bags for the former `@lmthing/css/components/computer/ide-file-tree.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.ide-file-tree__icon` */
export const IDE_FILE_TREE_ICON = {
  "flexShrink": 0,
  "color": "$muted-foreground"
} as const

/** `.ide-file-tree__icon--folder` */
export const IDE_FILE_TREE_ICON_FOLDER = {
  "color": "$primary"
} as const

/** `.ide-file-tree__context-item` */
export const IDE_FILE_TREE_CONTEXT_ITEM = {
  "display": "flex",
  "alignItems": "center",
  "gap": "$2",
  "paddingHorizontal": "$2",
  "paddingVertical": "$1.5",
  "fontSize": "$sm",
  "cursor": "pointer",
  "hoverStyle": {
    "backgroundColor": "$accent"
  },
  "borderRadius": "$radius",
  "outlineWidth": 0,
  "outlineStyle": "none"
} as const

/** `.ide-file-tree__context-item--danger` */
export const IDE_FILE_TREE_CONTEXT_ITEM_DANGER = {
  "color": "$destructive"
} as const

/** `.ide-file-tree__dialog-title` */
export const IDE_FILE_TREE_DIALOG_TITLE = {
  "fontSize": "$lg",
  "fontWeight": "$semibold",
  "marginBottom": "$4"
} as const

/** `.ide-file-tree__dialog-input` */
export const IDE_FILE_TREE_DIALOG_INPUT = {
  "width": "100%",
  "paddingHorizontal": "$3",
  "paddingVertical": "$2",
  "backgroundColor": "$background",
  "borderRadius": "$radius",
  "borderWidth": 1,
  "borderColor": "$border",
  "focusStyle": {
    "borderColor": "$primary"
  },
  "outlineWidth": 0,
  "outlineStyle": "none",
  "fontSize": "$sm"
} as const


/**
 * `.ide-file-tree__context-menu` — the floating menu panel. Recovered from the stylesheet as props;
 * the class had stopped applying when the stylesheet stopped being imported.
 */
export const IDE_FILE_TREE_CONTEXT_MENU = {
  minWidth: 160,
  overflow: 'hidden',
  borderRadius: '$radius-md',
  borderWidth: 1,
  borderColor: '$border',
  backgroundColor: '$popover',
  padding: '$1',
  shadowColor: 'rgba(0,0,0,0.1)', // ds-lint-ok: shadow alpha-black
  shadowOffset: { width: 0, height: 10 },
  shadowRadius: 15,
} as const

/** `.ide-file-tree__dialog-content` — the centred dialog panel (the `translate(-50%)` trick). */
export const IDE_FILE_TREE_DIALOG_CONTENT = {
  width: 384,
  borderRadius: '$radius-lg',
  borderWidth: 1,
  borderColor: '$border',
  backgroundColor: '$card',
  padding: '$6',
  shadowColor: 'rgba(0,0,0,0.1)', // ds-lint-ok: shadow alpha-black
  shadowOffset: { width: 0, height: 20 },
  shadowRadius: 25,
} as const
