/**
 * Prop bags for the former `libs/ui/src/studio/knowledge/field/field-tree/FieldTree.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.field-tree-node__icon` */
export const FIELD_TREE_NODE_ICON = {
  "width": "1rem",
  "height": "1rem",
  "flexShrink": 0
} as const

/** `.field-tree-node__icon--chevron` */
export const FIELD_TREE_NODE_ICON_CHEVRON = {
  "width": "0.875rem",
  "height": "0.875rem",
  "flexShrink": 0,
  "color": "var(--color-muted-foreground)"
} as const

/** `.field-tree-node__icon--folder` */
export const FIELD_TREE_NODE_ICON_FOLDER = {
  "color": "var(--color-primary)"
} as const

/** `.field-tree-node__icon--file` */
export const FIELD_TREE_NODE_ICON_FILE = {
  "color": "var(--color-muted-foreground)"
} as const

/** `.field-tree-node__spacer` */
export const FIELD_TREE_NODE_SPACER = {
  "width": "1.5rem",
  "flexShrink": 0
} as const

/** `.field-tree-node__label` */
export const FIELD_TREE_NODE_LABEL = {
  "fontSize": "0.875rem",
  "fontWeight": "500",
  "overflow": "hidden",
  "textOverflow": "ellipsis",
  "whiteSpace": "nowrap",
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "0%"
} as const

/** `.field-tree-context-menu__backdrop` */
export const FIELD_TREE_CONTEXT_MENU_BACKDROP = {
  "position": "fixed",
  "inset": "0",
  "zIndex": "40"
} as const

/** `.field-tree-context-menu__item--destructive` */
export const FIELD_TREE_CONTEXT_MENU_ITEM_DESTRUCTIVE = {
  "color": "var(--color-destructive)"
} as const

/** `.field-tree-context-menu__item-icon` */
export const FIELD_TREE_CONTEXT_MENU_ITEM_ICON = {
  "width": "1rem",
  "height": "1rem",
  "color": "var(--color-muted-foreground)"
} as const
