/**
 * Prop bags for the former `@lmthing/css/components/agent/builder/index.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.actions-panel__header-row` */
export const ACTIONS_PANEL_HEADER_ROW = {
  "display": "flex",
  "justifyContent": "space-between",
  "alignItems": "center"
} as const

/** `.actions-panel__empty` */
export const ACTIONS_PANEL_EMPTY = {
  "textAlign": "center",
  "paddingVertical": "3rem",
  "paddingHorizontal": "0"
} as const

/** `.actions-panel__empty-caption` */
export const ACTIONS_PANEL_EMPTY_CAPTION = {
  "marginHorizontal": "auto",
  "marginBottom": "$4",
  "maxWidth": "200px"
} as const

/** `.actions-panel__footer-caption` */
export const ACTIONS_PANEL_FOOTER_CAPTION = {
  "textAlign": "center",
  "display": "block"
} as const

/** `.actions-panel__card-row` */
export const ACTIONS_PANEL_CARD_ROW = {
  "display": "flex",
  "alignItems": "flex-start"
} as const

/** `.actions-panel__card-title-row` */
export const ACTIONS_PANEL_CARD_TITLE_ROW = {
  "display": "flex",
  "alignItems": "center",
  "marginBottom": "$1"
} as const

/** `.actions-panel__card-label` */
export const ACTIONS_PANEL_CARD_LABEL = {
  "overflow": "hidden",
  "color": "$ellipsis",
  "whiteSpace": "nowrap"
} as const

/** `.actions-panel__card-description` */
export const ACTIONS_PANEL_CARD_DESCRIPTION = {
  "marginTop": "0.125rem"
} as const

/** `.actions-panel__card-meta-row` */
export const ACTIONS_PANEL_CARD_META_ROW = {
  "marginTop": "$2"
} as const

/** `.actions-panel__badge-sm` */
export const ACTIONS_PANEL_BADGE_SM = {
  "fontSize": "0.625rem"
} as const

/** `.agent-builder__textarea` */
export const AGENT_BUILDER_TEXTAREA = {
  "fontFamily": "$mono",
  "resize": "vertical",
  "minHeight": "240px"
} as const

/** `.agent-header__left` */
export const AGENT_HEADER_LEFT = {
  "display": "flex",
  "alignItems": "center",
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "0%",
  "minWidth": 0,
  "gap": "0.75rem"
} as const

/** `.agent-header__icon` */
export const AGENT_HEADER_ICON = {
  "width": "$4",
  "height": "$4"
} as const

/** `.agent-header__right` */
export const AGENT_HEADER_RIGHT = {
  "display": "flex",
  "alignItems": "center",
  "flexShrink": 0
} as const

/** `.chat-fab__icon` */
export const CHAT_FAB_ICON = {
  "width": "1.25rem",
  "height": "1.25rem"
} as const

/** `.create-agent-inline` */
export const CREATE_AGENT_INLINE = {
  "marginBottom": "1.5rem"
} as const

/** `.create-agent-inline__header-row` */
export const CREATE_AGENT_INLINE_HEADER_ROW = {
  "display": "flex",
  "justifyContent": "space-between",
  "alignItems": "flex-start"
} as const

/** `.create-agent-inline__header-left` */
export const CREATE_AGENT_INLINE_HEADER_LEFT = {
  "display": "flex",
  "alignItems": "center"
} as const

/** `.create-agent-inline__avatar-icon` */
export const CREATE_AGENT_INLINE_AVATAR_ICON = {
  "width": "$5",
  "height": "$5",
  "color": "white"
} as const

/** `.create-agent-inline__close-icon` */
export const CREATE_AGENT_INLINE_CLOSE_ICON = {
  "width": "$4",
  "height": "$4"
} as const

/** `.create-agent-inline__actions` */
export const CREATE_AGENT_INLINE_ACTIONS = {
  "paddingTop": "0.25rem"
} as const

/** `.create-agent-inline__btn` */
export const CREATE_AGENT_INLINE_BTN = {
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "0%"
} as const

/** `.prompt-preview__header` */
export const PROMPT_PREVIEW_HEADER = {
  "cursor": "pointer",
  "userSelect": "none"
} as const

/** `.prompt-preview__header-row` */
export const PROMPT_PREVIEW_HEADER_ROW = {
  "display": "flex",
  "justifyContent": "space-between",
  "alignItems": "center"
} as const

/** `.prompt-preview__header-left` */
export const PROMPT_PREVIEW_HEADER_LEFT = {
  "display": "flex",
  "alignItems": "center"
} as const

/** `.prompt-preview__empty` */
export const PROMPT_PREVIEW_EMPTY = {
  "textAlign": "center",
  "paddingVertical": "2rem",
  "paddingHorizontal": "0"
} as const

/** `.prompt-preview__badge` */
export const PROMPT_PREVIEW_BADGE = {
  "fontSize": "0.625rem"
} as const

/** `.prompt-preview__footer-row` */
export const PROMPT_PREVIEW_FOOTER_ROW = {
  "display": "flex",
  "justifyContent": "space-between",
  "alignItems": "center"
} as const

/** `.save-agent-modal__header-row` */
export const SAVE_AGENT_MODAL_HEADER_ROW = {
  "display": "flex",
  "alignItems": "center"
} as const

/** `.save-agent-modal__icon` */
export const SAVE_AGENT_MODAL_ICON = {
  "width": "$5",
  "height": "$5",
  "color": "white"
} as const

/** `.save-agent-modal__form` */
export const SAVE_AGENT_MODAL_FORM = {
  "paddingVertical": "1.5rem",
  "paddingHorizontal": "1.5rem"
} as const

/** `.save-agent-modal__footer` */
export const SAVE_AGENT_MODAL_FOOTER = {
  "display": "flex",
  "justifyContent": "flex-end",
  "gap": "0.75rem"
} as const

/** `.saved-agents-list` */
export const SAVED_AGENTS_LIST = {
  "marginHorizontal": "auto",
  "maxWidth": "64rem",
  "paddingVertical": "1.5rem",
  "paddingHorizontal": "1.5rem"
} as const

/** `.saved-agents-list__header` */
export const SAVED_AGENTS_LIST_HEADER = {
  "display": "flex",
  "justifyContent": "space-between",
  "alignItems": "center",
  "marginBottom": "2rem"
} as const

/** `.saved-agents-list__subtitle` */
export const SAVED_AGENTS_LIST_SUBTITLE = {
  "marginTop": "0.25rem"
} as const

/** `.saved-agents-list__empty` */
export const SAVED_AGENTS_LIST_EMPTY = {
  "textAlign": "center",
  "paddingVertical": "4rem",
  "paddingHorizontal": "0"
} as const

/** `.saved-agents-list__empty-caption` */
export const SAVED_AGENTS_LIST_EMPTY_CAPTION = {
  "marginHorizontal": "auto",
  "maxWidth": "28rem",
  "marginTop": "0.5rem"
} as const

/** `.saved-agents-list__card-header` */
export const SAVED_AGENTS_LIST_CARD_HEADER = {
  "display": "flex",
  "justifyContent": "space-between",
  "alignItems": "flex-start",
  "marginBottom": "0.75rem"
} as const

/** `.saved-agents-list__card-name` */
export const SAVED_AGENTS_LIST_CARD_NAME = {
  "fontWeight": "$semibold"
} as const

/** `.saved-agents-list__card-description` */
export const SAVED_AGENTS_LIST_CARD_DESCRIPTION = {
  "overflow": "hidden",
  "marginTop": "0.25rem",
  "WebkitLineClamp": "2",
  "display": "-webkit-box",
  "WebkitBoxOrient": "vertical"
} as const

/** `.saved-agents-list__badge-sm` */
export const SAVED_AGENTS_LIST_BADGE_SM = {
  "fontSize": "0.625rem"
} as const

/** `.saved-agents-list__card-footer` */
export const SAVED_AGENTS_LIST_CARD_FOOTER = {
  "display": "flex",
  "justifyContent": "space-between",
  "alignItems": "center"
} as const

