/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteRouteImport } from './routes/studio/route'
import { Route as ComputerRouteRouteImport } from './routes/computer/route'
import { Route as ChatRouteRouteImport } from './routes/chat/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudioIndexRouteImport } from './routes/studio/index'
import { Route as ComputerIndexRouteImport } from './routes/computer/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ComputerTerminalRouteImport } from './routes/computer/terminal'
import { Route as ComputerSettingsRouteImport } from './routes/computer/settings'
import { Route as ComputerLoginRouteImport } from './routes/computer/login'
import { Route as ComputerDashboardRouteImport } from './routes/computer/dashboard'
import { Route as StudioProjectIdRouteRouteImport } from './routes/studio/$projectId/route'
import { Route as StudioThingIndexRouteImport } from './routes/studio/thing/index'
import { Route as StudioProjectIdIndexRouteImport } from './routes/studio/$projectId/index'
import { Route as ComputerSpacesIndexRouteImport } from './routes/computer/spaces/index'
import { Route as StudioProjectIdSpaceIdRouteRouteImport } from './routes/studio/$projectId/$spaceId/route'
import { Route as StudioProjectIdSpaceIdIndexRouteImport } from './routes/studio/$projectId/$spaceId/index'
import { Route as ComputerSpacesSpaceIdIndexRouteImport } from './routes/computer/spaces/$spaceId/index'
import { Route as ComputerSpacesSpaceIdLogsRouteImport } from './routes/computer/spaces/$spaceId/logs'
import { Route as ComputerSpacesSpaceIdConfigRouteImport } from './routes/computer/spaces/$spaceId/config'
import { Route as StudioProjectIdSpaceIdWorkflowIndexRouteImport } from './routes/studio/$projectId/$spaceId/workflow/index'
import { Route as StudioProjectIdSpaceIdSettingsIndexRouteImport } from './routes/studio/$projectId/$spaceId/settings/index'
import { Route as StudioProjectIdSpaceIdRawIndexRouteImport } from './routes/studio/$projectId/$spaceId/raw/index'
import { Route as StudioProjectIdSpaceIdKnowledgeIndexRouteImport } from './routes/studio/$projectId/$spaceId/knowledge/index'
import { Route as StudioProjectIdSpaceIdFunctionsIndexRouteImport } from './routes/studio/$projectId/$spaceId/functions/index'
import { Route as StudioProjectIdSpaceIdComponentsIndexRouteImport } from './routes/studio/$projectId/$spaceId/components/index'
import { Route as StudioProjectIdSpaceIdAgentIndexRouteImport } from './routes/studio/$projectId/$spaceId/agent/index'
import { Route as StudioProjectIdSpaceIdWorkflowNewIndexRouteImport } from './routes/studio/$projectId/$spaceId/workflow/new/index'
import { Route as StudioProjectIdSpaceIdWorkflowWorkflowIdIndexRouteImport } from './routes/studio/$projectId/$spaceId/workflow/$workflowId/index'
import { Route as StudioProjectIdSpaceIdSettingsPackagesIndexRouteImport } from './routes/studio/$projectId/$spaceId/settings/packages/index'
import { Route as StudioProjectIdSpaceIdSettingsEnvIndexRouteImport } from './routes/studio/$projectId/$spaceId/settings/env/index'
import { Route as StudioProjectIdSpaceIdKnowledgeFieldIdIndexRouteImport } from './routes/studio/$projectId/$spaceId/knowledge/$fieldId/index'
import { Route as StudioProjectIdSpaceIdAgentNewIndexRouteImport } from './routes/studio/$projectId/$spaceId/agent/new/index'
import { Route as StudioProjectIdSpaceIdAgentAgentIdIndexRouteImport } from './routes/studio/$projectId/$spaceId/agent/$agentId/index'
import { Route as StudioProjectIdSpaceIdKnowledgeDomainDomainIdIndexRouteImport } from './routes/studio/$projectId/$spaceId/knowledge/domain/$domainId/index'
import { Route as StudioProjectIdSpaceIdAgentAgentIdChatIndexRouteImport } from './routes/studio/$projectId/$spaceId/agent/$agentId/chat/index'
import { Route as StudioProjectIdSpaceIdWorkflowWorkflowIdStepStepIdIndexRouteImport } from './routes/studio/$projectId/$spaceId/workflow/$workflowId/step/$stepId/index'
import { Route as StudioProjectIdSpaceIdKnowledgeFieldIdSubjectIdTopicIdIndexRouteImport } from './routes/studio/$projectId/$spaceId/knowledge/$fieldId/$subjectId/$topicId/index'
import { Route as StudioProjectIdSpaceIdAgentAgentIdWorkflowWorkflowIdIndexRouteImport } from './routes/studio/$projectId/$spaceId/agent/$agentId/workflow/$workflowId/index'
import { Route as StudioProjectIdSpaceIdAgentAgentIdChatConversationIdIndexRouteImport } from './routes/studio/$projectId/$spaceId/agent/$agentId/chat/$conversationId/index'

const StudioRouteRoute = StudioRouteRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerRouteRoute = ComputerRouteRouteImport.update({
  id: '/computer',
  path: '/computer',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRouteRoute = ChatRouteRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const ComputerIndexRoute = ComputerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ComputerRouteRoute,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ChatRouteRoute,
} as any)
const ComputerTerminalRoute = ComputerTerminalRouteImport.update({
  id: '/terminal',
  path: '/terminal',
  getParentRoute: () => ComputerRouteRoute,
} as any)
const ComputerSettingsRoute = ComputerSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ComputerRouteRoute,
} as any)
const ComputerLoginRoute = ComputerLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => ComputerRouteRoute,
} as any)
const ComputerDashboardRoute = ComputerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ComputerRouteRoute,
} as any)
const StudioProjectIdRouteRoute = StudioProjectIdRouteRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioThingIndexRoute = StudioThingIndexRouteImport.update({
  id: '/thing/',
  path: '/thing/',
  getParentRoute: () => StudioRouteRoute,
} as any)
const StudioProjectIdIndexRoute = StudioProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioProjectIdRouteRoute,
} as any)
const ComputerSpacesIndexRoute = ComputerSpacesIndexRouteImport.update({
  id: '/spaces/',
  path: '/spaces/',
  getParentRoute: () => ComputerRouteRoute,
} as any)
const StudioProjectIdSpaceIdRouteRoute =
  StudioProjectIdSpaceIdRouteRouteImport.update({
    id: '/$spaceId',
    path: '/$spaceId',
    getParentRoute: () => StudioProjectIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdIndexRoute =
  StudioProjectIdSpaceIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const ComputerSpacesSpaceIdIndexRoute =
  ComputerSpacesSpaceIdIndexRouteImport.update({
    id: '/spaces/$spaceId/',
    path: '/spaces/$spaceId/',
    getParentRoute: () => ComputerRouteRoute,
  } as any)
const ComputerSpacesSpaceIdLogsRoute =
  ComputerSpacesSpaceIdLogsRouteImport.update({
    id: '/spaces/$spaceId/logs',
    path: '/spaces/$spaceId/logs',
    getParentRoute: () => ComputerRouteRoute,
  } as any)
const ComputerSpacesSpaceIdConfigRoute =
  ComputerSpacesSpaceIdConfigRouteImport.update({
    id: '/spaces/$spaceId/config',
    path: '/spaces/$spaceId/config',
    getParentRoute: () => ComputerRouteRoute,
  } as any)
const StudioProjectIdSpaceIdWorkflowIndexRoute =
  StudioProjectIdSpaceIdWorkflowIndexRouteImport.update({
    id: '/workflow/',
    path: '/workflow/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdSettingsIndexRoute =
  StudioProjectIdSpaceIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdRawIndexRoute =
  StudioProjectIdSpaceIdRawIndexRouteImport.update({
    id: '/raw/',
    path: '/raw/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdKnowledgeIndexRoute =
  StudioProjectIdSpaceIdKnowledgeIndexRouteImport.update({
    id: '/knowledge/',
    path: '/knowledge/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdFunctionsIndexRoute =
  StudioProjectIdSpaceIdFunctionsIndexRouteImport.update({
    id: '/functions/',
    path: '/functions/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdComponentsIndexRoute =
  StudioProjectIdSpaceIdComponentsIndexRouteImport.update({
    id: '/components/',
    path: '/components/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdAgentIndexRoute =
  StudioProjectIdSpaceIdAgentIndexRouteImport.update({
    id: '/agent/',
    path: '/agent/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdWorkflowNewIndexRoute =
  StudioProjectIdSpaceIdWorkflowNewIndexRouteImport.update({
    id: '/workflow/new/',
    path: '/workflow/new/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdWorkflowWorkflowIdIndexRoute =
  StudioProjectIdSpaceIdWorkflowWorkflowIdIndexRouteImport.update({
    id: '/workflow/$workflowId/',
    path: '/workflow/$workflowId/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdSettingsPackagesIndexRoute =
  StudioProjectIdSpaceIdSettingsPackagesIndexRouteImport.update({
    id: '/settings/packages/',
    path: '/settings/packages/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdSettingsEnvIndexRoute =
  StudioProjectIdSpaceIdSettingsEnvIndexRouteImport.update({
    id: '/settings/env/',
    path: '/settings/env/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdKnowledgeFieldIdIndexRoute =
  StudioProjectIdSpaceIdKnowledgeFieldIdIndexRouteImport.update({
    id: '/knowledge/$fieldId/',
    path: '/knowledge/$fieldId/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdAgentNewIndexRoute =
  StudioProjectIdSpaceIdAgentNewIndexRouteImport.update({
    id: '/agent/new/',
    path: '/agent/new/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdAgentAgentIdIndexRoute =
  StudioProjectIdSpaceIdAgentAgentIdIndexRouteImport.update({
    id: '/agent/$agentId/',
    path: '/agent/$agentId/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdKnowledgeDomainDomainIdIndexRoute =
  StudioProjectIdSpaceIdKnowledgeDomainDomainIdIndexRouteImport.update({
    id: '/knowledge/domain/$domainId/',
    path: '/knowledge/domain/$domainId/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdAgentAgentIdChatIndexRoute =
  StudioProjectIdSpaceIdAgentAgentIdChatIndexRouteImport.update({
    id: '/agent/$agentId/chat/',
    path: '/agent/$agentId/chat/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdWorkflowWorkflowIdStepStepIdIndexRoute =
  StudioProjectIdSpaceIdWorkflowWorkflowIdStepStepIdIndexRouteImport.update({
    id: '/workflow/$workflowId/step/$stepId/',
    path: '/workflow/$workflowId/step/$stepId/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdKnowledgeFieldIdSubjectIdTopicIdIndexRoute =
  StudioProjectIdSpaceIdKnowledgeFieldIdSubjectIdTopicIdIndexRouteImport.update(
    {
      id: '/knowledge/$fieldId/$subjectId/$topicId/',
      path: '/knowledge/$fieldId/$subjectId/$topicId/',
      getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
    } as any,
  )
const StudioProjectIdSpaceIdAgentAgentIdWorkflowWorkflowIdIndexRoute =
  StudioProjectIdSpaceIdAgentAgentIdWorkflowWorkflowIdIndexRouteImport.update({
    id: '/agent/$agentId/workflow/$workflowId/',
    path: '/agent/$agentId/workflow/$workflowId/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)
const StudioProjectIdSpaceIdAgentAgentIdChatConversationIdIndexRoute =
  StudioProjectIdSpaceIdAgentAgentIdChatConversationIdIndexRouteImport.update({
    id: '/agent/$agentId/chat/$conversationId/',
    path: '/agent/$agentId/chat/$conversationId/',
    getParentRoute: () => StudioProjectIdSpaceIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/computer': typeof ComputerRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/studio/$projectId': typeof StudioProjectIdRouteRouteWithChildren
  '/computer/dashboard': typeof ComputerDashboardRoute
  '/computer/login': typeof ComputerLoginRoute
  '/computer/settings': typeof ComputerSettingsRoute
  '/computer/terminal': typeof ComputerTerminalRoute
  '/chat/': typeof ChatIndexRoute
  '/computer/': typeof ComputerIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/$projectId/$spaceId': typeof StudioProjectIdSpaceIdRouteRouteWithChildren
  '/computer/spaces/': typeof ComputerSpacesIndexRoute
  '/studio/$projectId/': typeof StudioProjectIdIndexRoute
  '/studio/thing/': typeof StudioThingIndexRoute
  '/computer/spaces/$spaceId/config': typeof ComputerSpacesSpaceIdConfigRoute
  '/computer/spaces/$spaceId/logs': typeof ComputerSpacesSpaceIdLogsRoute
  '/computer/spaces/$spaceId/': typeof ComputerSpacesSpaceIdIndexRoute
  '/studio/$projectId/$spaceId/': typeof StudioProjectIdSpaceIdIndexRoute
  '/studio/$projectId/$spaceId/agent/': typeof StudioProjectIdSpaceIdAgentIndexRoute
  '/studio/$projectId/$spaceId/components/': typeof StudioProjectIdSpaceIdComponentsIndexRoute
  '/studio/$projectId/$spaceId/functions/': typeof StudioProjectIdSpaceIdFunctionsIndexRoute
  '/studio/$projectId/$spaceId/knowledge/': typeof StudioProjectIdSpaceIdKnowledgeIndexRoute
  '/studio/$projectId/$spaceId/raw/': typeof StudioProjectIdSpaceIdRawIndexRoute
  '/studio/$projectId/$spaceId/settings/': typeof StudioProjectIdSpaceIdSettingsIndexRoute
  '/studio/$projectId/$spaceId/workflow/': typeof StudioProjectIdSpaceIdWorkflowIndexRoute
  '/studio/$projectId/$spaceId/agent/$agentId/': typeof StudioProjectIdSpaceIdAgentAgentIdIndexRoute
  '/studio/$projectId/$spaceId/agent/new/': typeof StudioProjectIdSpaceIdAgentNewIndexRoute
  '/studio/$projectId/$spaceId/knowledge/$fieldId/': typeof StudioProjectIdSpaceIdKnowledgeFieldIdIndexRoute
  '/studio/$projectId/$spaceId/settings/env/': typeof StudioProjectIdSpaceIdSettingsEnvIndexRoute
  '/studio/$projectId/$spaceId/settings/packages/': typeof StudioProjectIdSpaceIdSettingsPackagesIndexRoute
  '/studio/$projectId/$spaceId/workflow/$workflowId/': typeof StudioProjectIdSpaceIdWorkflowWorkflowIdIndexRoute
  '/studio/$projectId/$spaceId/workflow/new/': typeof StudioProjectIdSpaceIdWorkflowNewIndexRoute
  '/studio/$projectId/$spaceId/agent/$agentId/chat/': typeof StudioProjectIdSpaceIdAgentAgentIdChatIndexRoute
  '/studio/$projectId/$spaceId/knowledge/domain/$domainId/': typeof StudioProjectIdSpaceIdKnowledgeDomainDomainIdIndexRoute
  '/studio/$projectId/$spaceId/agent/$agentId/chat/$conversationId/': typeof StudioProjectIdSpaceIdAgentAgentIdChatConversationIdIndexRoute
  '/studio/$projectId/$spaceId/agent/$agentId/workflow/$workflowId/': typeof StudioProjectIdSpaceIdAgentAgentIdWorkflowWorkflowIdIndexRoute
  '/studio/$projectId/$spaceId/knowledge/$fieldId/$subjectId/$topicId/': typeof StudioProjectIdSpaceIdKnowledgeFieldIdSubjectIdTopicIdIndexRoute
  '/studio/$projectId/$spaceId/workflow/$workflowId/step/$stepId/': typeof StudioProjectIdSpaceIdWorkflowWorkflowIdStepStepIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/computer/dashboard': typeof ComputerDashboardRoute
  '/computer/login': typeof ComputerLoginRoute
  '/computer/settings': typeof ComputerSettingsRoute
  '/computer/terminal': typeof ComputerTerminalRoute
  '/chat': typeof ChatIndexRoute
  '/computer': typeof ComputerIndexRoute
  '/studio': typeof StudioIndexRoute
  '/computer/spaces': typeof ComputerSpacesIndexRoute
  '/studio/$projectId': typeof StudioProjectIdIndexRoute
  '/studio/thing': typeof StudioThingIndexRoute
  '/computer/spaces/$spaceId/config': typeof ComputerSpacesSpaceIdConfigRoute
  '/computer/spaces/$spaceId/logs': typeof ComputerSpacesSpaceIdLogsRoute
  '/computer/spaces/$spaceId': typeof ComputerSpacesSpaceIdIndexRoute
  '/studio/$projectId/$spaceId': typeof StudioProjectIdSpaceIdIndexRoute
  '/studio/$projectId/$spaceId/agent': typeof StudioProjectIdSpaceIdAgentIndexRoute
  '/studio/$projectId/$spaceId/components': typeof StudioProjectIdSpaceIdComponentsIndexRoute
  '/studio/$projectId/$spaceId/functions': typeof StudioProjectIdSpaceIdFunctionsIndexRoute
  '/studio/$projectId/$spaceId/knowledge': typeof StudioProjectIdSpaceIdKnowledgeIndexRoute
  '/studio/$projectId/$spaceId/raw': typeof StudioProjectIdSpaceIdRawIndexRoute
  '/studio/$projectId/$spaceId/settings': typeof StudioProjectIdSpaceIdSettingsIndexRoute
  '/studio/$projectId/$spaceId/workflow': typeof StudioProjectIdSpaceIdWorkflowIndexRoute
  '/studio/$projectId/$spaceId/agent/$agentId': typeof StudioProjectIdSpaceIdAgentAgentIdIndexRoute
  '/studio/$projectId/$spaceId/agent/new': typeof StudioProjectIdSpaceIdAgentNewIndexRoute
  '/studio/$projectId/$spaceId/knowledge/$fieldId': typeof StudioProjectIdSpaceIdKnowledgeFieldIdIndexRoute
  '/studio/$projectId/$spaceId/settings/env': typeof StudioProjectIdSpaceIdSettingsEnvIndexRoute
  '/studio/$projectId/$spaceId/settings/packages': typeof StudioProjectIdSpaceIdSettingsPackagesIndexRoute
  '/studio/$projectId/$spaceId/workflow/$workflowId': typeof StudioProjectIdSpaceIdWorkflowWorkflowIdIndexRoute
  '/studio/$projectId/$spaceId/workflow/new': typeof StudioProjectIdSpaceIdWorkflowNewIndexRoute
  '/studio/$projectId/$spaceId/agent/$agentId/chat': typeof StudioProjectIdSpaceIdAgentAgentIdChatIndexRoute
  '/studio/$projectId/$spaceId/knowledge/domain/$domainId': typeof StudioProjectIdSpaceIdKnowledgeDomainDomainIdIndexRoute
  '/studio/$projectId/$spaceId/agent/$agentId/chat/$conversationId': typeof StudioProjectIdSpaceIdAgentAgentIdChatConversationIdIndexRoute
  '/studio/$projectId/$spaceId/agent/$agentId/workflow/$workflowId': typeof StudioProjectIdSpaceIdAgentAgentIdWorkflowWorkflowIdIndexRoute
  '/studio/$projectId/$spaceId/knowledge/$fieldId/$subjectId/$topicId': typeof StudioProjectIdSpaceIdKnowledgeFieldIdSubjectIdTopicIdIndexRoute
  '/studio/$projectId/$spaceId/workflow/$workflowId/step/$stepId': typeof StudioProjectIdSpaceIdWorkflowWorkflowIdStepStepIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRouteRouteWithChildren
  '/computer': typeof ComputerRouteRouteWithChildren
  '/studio': typeof StudioRouteRouteWithChildren
  '/studio/$projectId': typeof StudioProjectIdRouteRouteWithChildren
  '/computer/dashboard': typeof ComputerDashboardRoute
  '/computer/login': typeof ComputerLoginRoute
  '/computer/settings': typeof ComputerSettingsRoute
  '/computer/terminal': typeof ComputerTerminalRoute
  '/chat/': typeof ChatIndexRoute
  '/computer/': typeof ComputerIndexRoute
  '/studio/': typeof StudioIndexRoute
  '/studio/$projectId/$spaceId': typeof StudioProjectIdSpaceIdRouteRouteWithChildren
  '/computer/spaces/': typeof ComputerSpacesIndexRoute
  '/studio/$projectId/': typeof StudioProjectIdIndexRoute
  '/studio/thing/': typeof StudioThingIndexRoute
  '/computer/spaces/$spaceId/config': typeof ComputerSpacesSpaceIdConfigRoute
  '/computer/spaces/$spaceId/logs': typeof ComputerSpacesSpaceIdLogsRoute
  '/computer/spaces/$spaceId/': typeof ComputerSpacesSpaceIdIndexRoute
  '/studio/$projectId/$spaceId/': typeof StudioProjectIdSpaceIdIndexRoute
  '/studio/$projectId/$spaceId/agent/': typeof StudioProjectIdSpaceIdAgentIndexRoute
  '/studio/$projectId/$spaceId/components/': typeof StudioProjectIdSpaceIdComponentsIndexRoute
  '/studio/$projectId/$spaceId/functions/': typeof StudioProjectIdSpaceIdFunctionsIndexRoute
  '/studio/$projectId/$spaceId/knowledge/': typeof StudioProjectIdSpaceIdKnowledgeIndexRoute
  '/studio/$projectId/$spaceId/raw/': typeof StudioProjectIdSpaceIdRawIndexRoute
  '/studio/$projectId/$spaceId/settings/': typeof StudioProjectIdSpaceIdSettingsIndexRoute
  '/studio/$projectId/$spaceId/workflow/': typeof StudioProjectIdSpaceIdWorkflowIndexRoute
  '/studio/$projectId/$spaceId/agent/$agentId/': typeof StudioProjectIdSpaceIdAgentAgentIdIndexRoute
  '/studio/$projectId/$spaceId/agent/new/': typeof StudioProjectIdSpaceIdAgentNewIndexRoute
  '/studio/$projectId/$spaceId/knowledge/$fieldId/': typeof StudioProjectIdSpaceIdKnowledgeFieldIdIndexRoute
  '/studio/$projectId/$spaceId/settings/env/': typeof StudioProjectIdSpaceIdSettingsEnvIndexRoute
  '/studio/$projectId/$spaceId/settings/packages/': typeof StudioProjectIdSpaceIdSettingsPackagesIndexRoute
  '/studio/$projectId/$spaceId/workflow/$workflowId/': typeof StudioProjectIdSpaceIdWorkflowWorkflowIdIndexRoute
  '/studio/$projectId/$spaceId/workflow/new/': typeof StudioProjectIdSpaceIdWorkflowNewIndexRoute
  '/studio/$projectId/$spaceId/agent/$agentId/chat/': typeof StudioProjectIdSpaceIdAgentAgentIdChatIndexRoute
  '/studio/$projectId/$spaceId/knowledge/domain/$domainId/': typeof StudioProjectIdSpaceIdKnowledgeDomainDomainIdIndexRoute
  '/studio/$projectId/$spaceId/agent/$agentId/chat/$conversationId/': typeof StudioProjectIdSpaceIdAgentAgentIdChatConversationIdIndexRoute
  '/studio/$projectId/$spaceId/agent/$agentId/workflow/$workflowId/': typeof StudioProjectIdSpaceIdAgentAgentIdWorkflowWorkflowIdIndexRoute
  '/studio/$projectId/$spaceId/knowledge/$fieldId/$subjectId/$topicId/': typeof StudioProjectIdSpaceIdKnowledgeFieldIdSubjectIdTopicIdIndexRoute
  '/studio/$projectId/$spaceId/workflow/$workflowId/step/$stepId/': typeof StudioProjectIdSpaceIdWorkflowWorkflowIdStepStepIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/computer'
    | '/studio'
    | '/studio/$projectId'
    | '/computer/dashboard'
    | '/computer/login'
    | '/computer/settings'
    | '/computer/terminal'
    | '/chat/'
    | '/computer/'
    | '/studio/'
    | '/studio/$projectId/$spaceId'
    | '/computer/spaces/'
    | '/studio/$projectId/'
    | '/studio/thing/'
    | '/computer/spaces/$spaceId/config'
    | '/computer/spaces/$spaceId/logs'
    | '/computer/spaces/$spaceId/'
    | '/studio/$projectId/$spaceId/'
    | '/studio/$projectId/$spaceId/agent/'
    | '/studio/$projectId/$spaceId/components/'
    | '/studio/$projectId/$spaceId/functions/'
    | '/studio/$projectId/$spaceId/knowledge/'
    | '/studio/$projectId/$spaceId/raw/'
    | '/studio/$projectId/$spaceId/settings/'
    | '/studio/$projectId/$spaceId/workflow/'
    | '/studio/$projectId/$spaceId/agent/$agentId/'
    | '/studio/$projectId/$spaceId/agent/new/'
    | '/studio/$projectId/$spaceId/knowledge/$fieldId/'
    | '/studio/$projectId/$spaceId/settings/env/'
    | '/studio/$projectId/$spaceId/settings/packages/'
    | '/studio/$projectId/$spaceId/workflow/$workflowId/'
    | '/studio/$projectId/$spaceId/workflow/new/'
    | '/studio/$projectId/$spaceId/agent/$agentId/chat/'
    | '/studio/$projectId/$spaceId/knowledge/domain/$domainId/'
    | '/studio/$projectId/$spaceId/agent/$agentId/chat/$conversationId/'
    | '/studio/$projectId/$spaceId/agent/$agentId/workflow/$workflowId/'
    | '/studio/$projectId/$spaceId/knowledge/$fieldId/$subjectId/$topicId/'
    | '/studio/$projectId/$spaceId/workflow/$workflowId/step/$stepId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/computer/dashboard'
    | '/computer/login'
    | '/computer/settings'
    | '/computer/terminal'
    | '/chat'
    | '/computer'
    | '/studio'
    | '/computer/spaces'
    | '/studio/$projectId'
    | '/studio/thing'
    | '/computer/spaces/$spaceId/config'
    | '/computer/spaces/$spaceId/logs'
    | '/computer/spaces/$spaceId'
    | '/studio/$projectId/$spaceId'
    | '/studio/$projectId/$spaceId/agent'
    | '/studio/$projectId/$spaceId/components'
    | '/studio/$projectId/$spaceId/functions'
    | '/studio/$projectId/$spaceId/knowledge'
    | '/studio/$projectId/$spaceId/raw'
    | '/studio/$projectId/$spaceId/settings'
    | '/studio/$projectId/$spaceId/workflow'
    | '/studio/$projectId/$spaceId/agent/$agentId'
    | '/studio/$projectId/$spaceId/agent/new'
    | '/studio/$projectId/$spaceId/knowledge/$fieldId'
    | '/studio/$projectId/$spaceId/settings/env'
    | '/studio/$projectId/$spaceId/settings/packages'
    | '/studio/$projectId/$spaceId/workflow/$workflowId'
    | '/studio/$projectId/$spaceId/workflow/new'
    | '/studio/$projectId/$spaceId/agent/$agentId/chat'
    | '/studio/$projectId/$spaceId/knowledge/domain/$domainId'
    | '/studio/$projectId/$spaceId/agent/$agentId/chat/$conversationId'
    | '/studio/$projectId/$spaceId/agent/$agentId/workflow/$workflowId'
    | '/studio/$projectId/$spaceId/knowledge/$fieldId/$subjectId/$topicId'
    | '/studio/$projectId/$spaceId/workflow/$workflowId/step/$stepId'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/computer'
    | '/studio'
    | '/studio/$projectId'
    | '/computer/dashboard'
    | '/computer/login'
    | '/computer/settings'
    | '/computer/terminal'
    | '/chat/'
    | '/computer/'
    | '/studio/'
    | '/studio/$projectId/$spaceId'
    | '/computer/spaces/'
    | '/studio/$projectId/'
    | '/studio/thing/'
    | '/computer/spaces/$spaceId/config'
    | '/computer/spaces/$spaceId/logs'
    | '/computer/spaces/$spaceId/'
    | '/studio/$projectId/$spaceId/'
    | '/studio/$projectId/$spaceId/agent/'
    | '/studio/$projectId/$spaceId/components/'
    | '/studio/$projectId/$spaceId/functions/'
    | '/studio/$projectId/$spaceId/knowledge/'
    | '/studio/$projectId/$spaceId/raw/'
    | '/studio/$projectId/$spaceId/settings/'
    | '/studio/$projectId/$spaceId/workflow/'
    | '/studio/$projectId/$spaceId/agent/$agentId/'
    | '/studio/$projectId/$spaceId/agent/new/'
    | '/studio/$projectId/$spaceId/knowledge/$fieldId/'
    | '/studio/$projectId/$spaceId/settings/env/'
    | '/studio/$projectId/$spaceId/settings/packages/'
    | '/studio/$projectId/$spaceId/workflow/$workflowId/'
    | '/studio/$projectId/$spaceId/workflow/new/'
    | '/studio/$projectId/$spaceId/agent/$agentId/chat/'
    | '/studio/$projectId/$spaceId/knowledge/domain/$domainId/'
    | '/studio/$projectId/$spaceId/agent/$agentId/chat/$conversationId/'
    | '/studio/$projectId/$spaceId/agent/$agentId/workflow/$workflowId/'
    | '/studio/$projectId/$spaceId/knowledge/$fieldId/$subjectId/$topicId/'
    | '/studio/$projectId/$spaceId/workflow/$workflowId/step/$stepId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRouteRoute: typeof ChatRouteRouteWithChildren
  ComputerRouteRoute: typeof ComputerRouteRouteWithChildren
  StudioRouteRoute: typeof StudioRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer': {
      id: '/computer'
      path: '/computer'
      fullPath: '/computer'
      preLoaderRoute: typeof ComputerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/': {
      id: '/studio/'
      path: '/'
      fullPath: '/studio/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/computer/': {
      id: '/computer/'
      path: '/'
      fullPath: '/computer/'
      preLoaderRoute: typeof ComputerIndexRouteImport
      parentRoute: typeof ComputerRouteRoute
    }
    '/chat/': {
      id: '/chat/'
      path: '/'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof ChatRouteRoute
    }
    '/computer/terminal': {
      id: '/computer/terminal'
      path: '/terminal'
      fullPath: '/computer/terminal'
      preLoaderRoute: typeof ComputerTerminalRouteImport
      parentRoute: typeof ComputerRouteRoute
    }
    '/computer/settings': {
      id: '/computer/settings'
      path: '/settings'
      fullPath: '/computer/settings'
      preLoaderRoute: typeof ComputerSettingsRouteImport
      parentRoute: typeof ComputerRouteRoute
    }
    '/computer/login': {
      id: '/computer/login'
      path: '/login'
      fullPath: '/computer/login'
      preLoaderRoute: typeof ComputerLoginRouteImport
      parentRoute: typeof ComputerRouteRoute
    }
    '/computer/dashboard': {
      id: '/computer/dashboard'
      path: '/dashboard'
      fullPath: '/computer/dashboard'
      preLoaderRoute: typeof ComputerDashboardRouteImport
      parentRoute: typeof ComputerRouteRoute
    }
    '/studio/$projectId': {
      id: '/studio/$projectId'
      path: '/$projectId'
      fullPath: '/studio/$projectId'
      preLoaderRoute: typeof StudioProjectIdRouteRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/thing/': {
      id: '/studio/thing/'
      path: '/thing'
      fullPath: '/studio/thing/'
      preLoaderRoute: typeof StudioThingIndexRouteImport
      parentRoute: typeof StudioRouteRoute
    }
    '/studio/$projectId/': {
      id: '/studio/$projectId/'
      path: '/'
      fullPath: '/studio/$projectId/'
      preLoaderRoute: typeof StudioProjectIdIndexRouteImport
      parentRoute: typeof StudioProjectIdRouteRoute
    }
    '/computer/spaces/': {
      id: '/computer/spaces/'
      path: '/spaces'
      fullPath: '/computer/spaces/'
      preLoaderRoute: typeof ComputerSpacesIndexRouteImport
      parentRoute: typeof ComputerRouteRoute
    }
    '/studio/$projectId/$spaceId': {
      id: '/studio/$projectId/$spaceId'
      path: '/$spaceId'
      fullPath: '/studio/$projectId/$spaceId'
      preLoaderRoute: typeof StudioProjectIdSpaceIdRouteRouteImport
      parentRoute: typeof StudioProjectIdRouteRoute
    }
    '/studio/$projectId/$spaceId/': {
      id: '/studio/$projectId/$spaceId/'
      path: '/'
      fullPath: '/studio/$projectId/$spaceId/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/computer/spaces/$spaceId/': {
      id: '/computer/spaces/$spaceId/'
      path: '/spaces/$spaceId'
      fullPath: '/computer/spaces/$spaceId/'
      preLoaderRoute: typeof ComputerSpacesSpaceIdIndexRouteImport
      parentRoute: typeof ComputerRouteRoute
    }
    '/computer/spaces/$spaceId/logs': {
      id: '/computer/spaces/$spaceId/logs'
      path: '/spaces/$spaceId/logs'
      fullPath: '/computer/spaces/$spaceId/logs'
      preLoaderRoute: typeof ComputerSpacesSpaceIdLogsRouteImport
      parentRoute: typeof ComputerRouteRoute
    }
    '/computer/spaces/$spaceId/config': {
      id: '/computer/spaces/$spaceId/config'
      path: '/spaces/$spaceId/config'
      fullPath: '/computer/spaces/$spaceId/config'
      preLoaderRoute: typeof ComputerSpacesSpaceIdConfigRouteImport
      parentRoute: typeof ComputerRouteRoute
    }
    '/studio/$projectId/$spaceId/workflow/': {
      id: '/studio/$projectId/$spaceId/workflow/'
      path: '/workflow'
      fullPath: '/studio/$projectId/$spaceId/workflow/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdWorkflowIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/settings/': {
      id: '/studio/$projectId/$spaceId/settings/'
      path: '/settings'
      fullPath: '/studio/$projectId/$spaceId/settings/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdSettingsIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/raw/': {
      id: '/studio/$projectId/$spaceId/raw/'
      path: '/raw'
      fullPath: '/studio/$projectId/$spaceId/raw/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdRawIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/knowledge/': {
      id: '/studio/$projectId/$spaceId/knowledge/'
      path: '/knowledge'
      fullPath: '/studio/$projectId/$spaceId/knowledge/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdKnowledgeIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/functions/': {
      id: '/studio/$projectId/$spaceId/functions/'
      path: '/functions'
      fullPath: '/studio/$projectId/$spaceId/functions/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdFunctionsIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/components/': {
      id: '/studio/$projectId/$spaceId/components/'
      path: '/components'
      fullPath: '/studio/$projectId/$spaceId/components/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdComponentsIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/agent/': {
      id: '/studio/$projectId/$spaceId/agent/'
      path: '/agent'
      fullPath: '/studio/$projectId/$spaceId/agent/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdAgentIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/workflow/new/': {
      id: '/studio/$projectId/$spaceId/workflow/new/'
      path: '/workflow/new'
      fullPath: '/studio/$projectId/$spaceId/workflow/new/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdWorkflowNewIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/workflow/$workflowId/': {
      id: '/studio/$projectId/$spaceId/workflow/$workflowId/'
      path: '/workflow/$workflowId'
      fullPath: '/studio/$projectId/$spaceId/workflow/$workflowId/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdWorkflowWorkflowIdIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/settings/packages/': {
      id: '/studio/$projectId/$spaceId/settings/packages/'
      path: '/settings/packages'
      fullPath: '/studio/$projectId/$spaceId/settings/packages/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdSettingsPackagesIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/settings/env/': {
      id: '/studio/$projectId/$spaceId/settings/env/'
      path: '/settings/env'
      fullPath: '/studio/$projectId/$spaceId/settings/env/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdSettingsEnvIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/knowledge/$fieldId/': {
      id: '/studio/$projectId/$spaceId/knowledge/$fieldId/'
      path: '/knowledge/$fieldId'
      fullPath: '/studio/$projectId/$spaceId/knowledge/$fieldId/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdKnowledgeFieldIdIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/agent/new/': {
      id: '/studio/$projectId/$spaceId/agent/new/'
      path: '/agent/new'
      fullPath: '/studio/$projectId/$spaceId/agent/new/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdAgentNewIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/agent/$agentId/': {
      id: '/studio/$projectId/$spaceId/agent/$agentId/'
      path: '/agent/$agentId'
      fullPath: '/studio/$projectId/$spaceId/agent/$agentId/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdAgentAgentIdIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/knowledge/domain/$domainId/': {
      id: '/studio/$projectId/$spaceId/knowledge/domain/$domainId/'
      path: '/knowledge/domain/$domainId'
      fullPath: '/studio/$projectId/$spaceId/knowledge/domain/$domainId/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdKnowledgeDomainDomainIdIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/agent/$agentId/chat/': {
      id: '/studio/$projectId/$spaceId/agent/$agentId/chat/'
      path: '/agent/$agentId/chat'
      fullPath: '/studio/$projectId/$spaceId/agent/$agentId/chat/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdAgentAgentIdChatIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/workflow/$workflowId/step/$stepId/': {
      id: '/studio/$projectId/$spaceId/workflow/$workflowId/step/$stepId/'
      path: '/workflow/$workflowId/step/$stepId'
      fullPath: '/studio/$projectId/$spaceId/workflow/$workflowId/step/$stepId/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdWorkflowWorkflowIdStepStepIdIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/knowledge/$fieldId/$subjectId/$topicId/': {
      id: '/studio/$projectId/$spaceId/knowledge/$fieldId/$subjectId/$topicId/'
      path: '/knowledge/$fieldId/$subjectId/$topicId'
      fullPath: '/studio/$projectId/$spaceId/knowledge/$fieldId/$subjectId/$topicId/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdKnowledgeFieldIdSubjectIdTopicIdIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/agent/$agentId/workflow/$workflowId/': {
      id: '/studio/$projectId/$spaceId/agent/$agentId/workflow/$workflowId/'
      path: '/agent/$agentId/workflow/$workflowId'
      fullPath: '/studio/$projectId/$spaceId/agent/$agentId/workflow/$workflowId/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdAgentAgentIdWorkflowWorkflowIdIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
    '/studio/$projectId/$spaceId/agent/$agentId/chat/$conversationId/': {
      id: '/studio/$projectId/$spaceId/agent/$agentId/chat/$conversationId/'
      path: '/agent/$agentId/chat/$conversationId'
      fullPath: '/studio/$projectId/$spaceId/agent/$agentId/chat/$conversationId/'
      preLoaderRoute: typeof StudioProjectIdSpaceIdAgentAgentIdChatConversationIdIndexRouteImport
      parentRoute: typeof StudioProjectIdSpaceIdRouteRoute
    }
  }
}

interface ChatRouteRouteChildren {
  ChatIndexRoute: typeof ChatIndexRoute
}

const ChatRouteRouteChildren: ChatRouteRouteChildren = {
  ChatIndexRoute: ChatIndexRoute,
}

const ChatRouteRouteWithChildren = ChatRouteRoute._addFileChildren(
  ChatRouteRouteChildren,
)

interface ComputerRouteRouteChildren {
  ComputerDashboardRoute: typeof ComputerDashboardRoute
  ComputerLoginRoute: typeof ComputerLoginRoute
  ComputerSettingsRoute: typeof ComputerSettingsRoute
  ComputerTerminalRoute: typeof ComputerTerminalRoute
  ComputerIndexRoute: typeof ComputerIndexRoute
  ComputerSpacesIndexRoute: typeof ComputerSpacesIndexRoute
  ComputerSpacesSpaceIdConfigRoute: typeof ComputerSpacesSpaceIdConfigRoute
  ComputerSpacesSpaceIdLogsRoute: typeof ComputerSpacesSpaceIdLogsRoute
  ComputerSpacesSpaceIdIndexRoute: typeof ComputerSpacesSpaceIdIndexRoute
}

const ComputerRouteRouteChildren: ComputerRouteRouteChildren = {
  ComputerDashboardRoute: ComputerDashboardRoute,
  ComputerLoginRoute: ComputerLoginRoute,
  ComputerSettingsRoute: ComputerSettingsRoute,
  ComputerTerminalRoute: ComputerTerminalRoute,
  ComputerIndexRoute: ComputerIndexRoute,
  ComputerSpacesIndexRoute: ComputerSpacesIndexRoute,
  ComputerSpacesSpaceIdConfigRoute: ComputerSpacesSpaceIdConfigRoute,
  ComputerSpacesSpaceIdLogsRoute: ComputerSpacesSpaceIdLogsRoute,
  ComputerSpacesSpaceIdIndexRoute: ComputerSpacesSpaceIdIndexRoute,
}

const ComputerRouteRouteWithChildren = ComputerRouteRoute._addFileChildren(
  ComputerRouteRouteChildren,
)

interface StudioProjectIdSpaceIdRouteRouteChildren {
  StudioProjectIdSpaceIdIndexRoute: typeof StudioProjectIdSpaceIdIndexRoute
  StudioProjectIdSpaceIdAgentIndexRoute: typeof StudioProjectIdSpaceIdAgentIndexRoute
  StudioProjectIdSpaceIdComponentsIndexRoute: typeof StudioProjectIdSpaceIdComponentsIndexRoute
  StudioProjectIdSpaceIdFunctionsIndexRoute: typeof StudioProjectIdSpaceIdFunctionsIndexRoute
  StudioProjectIdSpaceIdKnowledgeIndexRoute: typeof StudioProjectIdSpaceIdKnowledgeIndexRoute
  StudioProjectIdSpaceIdRawIndexRoute: typeof StudioProjectIdSpaceIdRawIndexRoute
  StudioProjectIdSpaceIdSettingsIndexRoute: typeof StudioProjectIdSpaceIdSettingsIndexRoute
  StudioProjectIdSpaceIdWorkflowIndexRoute: typeof StudioProjectIdSpaceIdWorkflowIndexRoute
  StudioProjectIdSpaceIdAgentAgentIdIndexRoute: typeof StudioProjectIdSpaceIdAgentAgentIdIndexRoute
  StudioProjectIdSpaceIdAgentNewIndexRoute: typeof StudioProjectIdSpaceIdAgentNewIndexRoute
  StudioProjectIdSpaceIdKnowledgeFieldIdIndexRoute: typeof StudioProjectIdSpaceIdKnowledgeFieldIdIndexRoute
  StudioProjectIdSpaceIdSettingsEnvIndexRoute: typeof StudioProjectIdSpaceIdSettingsEnvIndexRoute
  StudioProjectIdSpaceIdSettingsPackagesIndexRoute: typeof StudioProjectIdSpaceIdSettingsPackagesIndexRoute
  StudioProjectIdSpaceIdWorkflowWorkflowIdIndexRoute: typeof StudioProjectIdSpaceIdWorkflowWorkflowIdIndexRoute
  StudioProjectIdSpaceIdWorkflowNewIndexRoute: typeof StudioProjectIdSpaceIdWorkflowNewIndexRoute
  StudioProjectIdSpaceIdAgentAgentIdChatIndexRoute: typeof StudioProjectIdSpaceIdAgentAgentIdChatIndexRoute
  StudioProjectIdSpaceIdKnowledgeDomainDomainIdIndexRoute: typeof StudioProjectIdSpaceIdKnowledgeDomainDomainIdIndexRoute
  StudioProjectIdSpaceIdAgentAgentIdChatConversationIdIndexRoute: typeof StudioProjectIdSpaceIdAgentAgentIdChatConversationIdIndexRoute
  StudioProjectIdSpaceIdAgentAgentIdWorkflowWorkflowIdIndexRoute: typeof StudioProjectIdSpaceIdAgentAgentIdWorkflowWorkflowIdIndexRoute
  StudioProjectIdSpaceIdKnowledgeFieldIdSubjectIdTopicIdIndexRoute: typeof StudioProjectIdSpaceIdKnowledgeFieldIdSubjectIdTopicIdIndexRoute
  StudioProjectIdSpaceIdWorkflowWorkflowIdStepStepIdIndexRoute: typeof StudioProjectIdSpaceIdWorkflowWorkflowIdStepStepIdIndexRoute
}

const StudioProjectIdSpaceIdRouteRouteChildren: StudioProjectIdSpaceIdRouteRouteChildren =
  {
    StudioProjectIdSpaceIdIndexRoute: StudioProjectIdSpaceIdIndexRoute,
    StudioProjectIdSpaceIdAgentIndexRoute:
      StudioProjectIdSpaceIdAgentIndexRoute,
    StudioProjectIdSpaceIdComponentsIndexRoute:
      StudioProjectIdSpaceIdComponentsIndexRoute,
    StudioProjectIdSpaceIdFunctionsIndexRoute:
      StudioProjectIdSpaceIdFunctionsIndexRoute,
    StudioProjectIdSpaceIdKnowledgeIndexRoute:
      StudioProjectIdSpaceIdKnowledgeIndexRoute,
    StudioProjectIdSpaceIdRawIndexRoute: StudioProjectIdSpaceIdRawIndexRoute,
    StudioProjectIdSpaceIdSettingsIndexRoute:
      StudioProjectIdSpaceIdSettingsIndexRoute,
    StudioProjectIdSpaceIdWorkflowIndexRoute:
      StudioProjectIdSpaceIdWorkflowIndexRoute,
    StudioProjectIdSpaceIdAgentAgentIdIndexRoute:
      StudioProjectIdSpaceIdAgentAgentIdIndexRoute,
    StudioProjectIdSpaceIdAgentNewIndexRoute:
      StudioProjectIdSpaceIdAgentNewIndexRoute,
    StudioProjectIdSpaceIdKnowledgeFieldIdIndexRoute:
      StudioProjectIdSpaceIdKnowledgeFieldIdIndexRoute,
    StudioProjectIdSpaceIdSettingsEnvIndexRoute:
      StudioProjectIdSpaceIdSettingsEnvIndexRoute,
    StudioProjectIdSpaceIdSettingsPackagesIndexRoute:
      StudioProjectIdSpaceIdSettingsPackagesIndexRoute,
    StudioProjectIdSpaceIdWorkflowWorkflowIdIndexRoute:
      StudioProjectIdSpaceIdWorkflowWorkflowIdIndexRoute,
    StudioProjectIdSpaceIdWorkflowNewIndexRoute:
      StudioProjectIdSpaceIdWorkflowNewIndexRoute,
    StudioProjectIdSpaceIdAgentAgentIdChatIndexRoute:
      StudioProjectIdSpaceIdAgentAgentIdChatIndexRoute,
    StudioProjectIdSpaceIdKnowledgeDomainDomainIdIndexRoute:
      StudioProjectIdSpaceIdKnowledgeDomainDomainIdIndexRoute,
    StudioProjectIdSpaceIdAgentAgentIdChatConversationIdIndexRoute:
      StudioProjectIdSpaceIdAgentAgentIdChatConversationIdIndexRoute,
    StudioProjectIdSpaceIdAgentAgentIdWorkflowWorkflowIdIndexRoute:
      StudioProjectIdSpaceIdAgentAgentIdWorkflowWorkflowIdIndexRoute,
    StudioProjectIdSpaceIdKnowledgeFieldIdSubjectIdTopicIdIndexRoute:
      StudioProjectIdSpaceIdKnowledgeFieldIdSubjectIdTopicIdIndexRoute,
    StudioProjectIdSpaceIdWorkflowWorkflowIdStepStepIdIndexRoute:
      StudioProjectIdSpaceIdWorkflowWorkflowIdStepStepIdIndexRoute,
  }

const StudioProjectIdSpaceIdRouteRouteWithChildren =
  StudioProjectIdSpaceIdRouteRoute._addFileChildren(
    StudioProjectIdSpaceIdRouteRouteChildren,
  )

interface StudioProjectIdRouteRouteChildren {
  StudioProjectIdSpaceIdRouteRoute: typeof StudioProjectIdSpaceIdRouteRouteWithChildren
  StudioProjectIdIndexRoute: typeof StudioProjectIdIndexRoute
}

const StudioProjectIdRouteRouteChildren: StudioProjectIdRouteRouteChildren = {
  StudioProjectIdSpaceIdRouteRoute:
    StudioProjectIdSpaceIdRouteRouteWithChildren,
  StudioProjectIdIndexRoute: StudioProjectIdIndexRoute,
}

const StudioProjectIdRouteRouteWithChildren =
  StudioProjectIdRouteRoute._addFileChildren(StudioProjectIdRouteRouteChildren)

interface StudioRouteRouteChildren {
  StudioProjectIdRouteRoute: typeof StudioProjectIdRouteRouteWithChildren
  StudioIndexRoute: typeof StudioIndexRoute
  StudioThingIndexRoute: typeof StudioThingIndexRoute
}

const StudioRouteRouteChildren: StudioRouteRouteChildren = {
  StudioProjectIdRouteRoute: StudioProjectIdRouteRouteWithChildren,
  StudioIndexRoute: StudioIndexRoute,
  StudioThingIndexRoute: StudioThingIndexRoute,
}

const StudioRouteRouteWithChildren = StudioRouteRoute._addFileChildren(
  StudioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRouteRoute: ChatRouteRouteWithChildren,
  ComputerRouteRoute: ComputerRouteRouteWithChildren,
  StudioRouteRoute: StudioRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
