/**
 * Prop bags for the former `@lmthing/css/components/space/index.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.space-list__header` */
export const SPACE_LIST_HEADER = {
  "display": "flex",
  "justifyContent": "space-between",
  "alignItems": "center"
} as const

/** `.space-list__invite-icon` */
export const SPACE_LIST_INVITE_ICON = {
  "width": "1rem",
  "height": "1rem"
} as const

/** `.space-list__search-icon` */
export const SPACE_LIST_SEARCH_ICON = {
  "width": "1rem",
  "height": "1rem",
  "position": "absolute",
  "left": "0.75rem",
  "top": "50%",
  "transform": "translateY(-50%)",
  "color": "var(--muted)"
} as const

/** `.space-list__search-input` */
export const SPACE_LIST_SEARCH_INPUT = {
  "paddingLeft": "2.25rem"
} as const

/** `.space-list__empty` */
export const SPACE_LIST_EMPTY = {
  "display": "flex",
  "flexDirection": "column",
  "alignItems": "center",
  "justifyContent": "center",
  "height": "12rem"
} as const

/** `.space-list__empty-icon` */
export const SPACE_LIST_EMPTY_ICON = {
  "width": "2.5rem",
  "height": "2.5rem",
  "opacity": "0.5"
} as const

/** `.space-list__user-list` */
export const SPACE_LIST_USER_LIST = {
  "paddingVertical": "0.5rem",
  "paddingHorizontal": "0.5rem"
} as const

/** `.space-list__user-name-row` */
export const SPACE_LIST_USER_NAME_ROW = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.25rem"
} as const

/** `.space-list__email-row` */
export const SPACE_LIST_EMAIL_ROW = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.25rem",
  "marginTop": "0.125rem"
} as const

/** `.space-list__email` */
export const SPACE_LIST_EMAIL = {
  "overflow": "hidden",
  "textOverflow": "ellipsis",
  "whiteSpace": "nowrap"
} as const

/** `.space-list__email-icon` */
export const SPACE_LIST_EMAIL_ICON = {
  "width": "0.75rem",
  "height": "0.75rem",
  "flexShrink": "0",
  "opacity": "0.5"
} as const

/** `.space-list__last-active-icon` */
export const SPACE_LIST_LAST_ACTIVE_ICON = {
  "width": "0.75rem",
  "height": "0.75rem"
} as const

/** `.space-list__status-badge` */
export const SPACE_LIST_STATUS_BADGE = {
  "fontSize": "0.625rem"
} as const

/** `.space-list__last-active` */
export const SPACE_LIST_LAST_ACTIVE = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.25rem",
  "fontSize": "0.6875rem"
} as const

/** `.space-list__invite-form-body` */
export const SPACE_LIST_INVITE_FORM_BODY = {
  "paddingVertical": "1.5rem",
  "paddingHorizontal": "1.5rem"
} as const

/** `.space-list__invite-role-item` */
export const SPACE_LIST_INVITE_ROLE_ITEM = {
  "cursor": "pointer"
} as const

/** `.space-list__invite-role-radio` */
export const SPACE_LIST_INVITE_ROLE_RADIO = {
  "marginRight": "0.75rem"
} as const

/** `.space-list__invite-actions` */
export const SPACE_LIST_INVITE_ACTIONS = {
  "paddingTop": "0.5rem"
} as const

/** `.space-list__invite-action-btn` */
export const SPACE_LIST_INVITE_ACTION_BTN = {
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "0%"
} as const

/** `.space-selector__trigger` */
export const SPACE_SELECTOR_TRIGGER = {
  "width": "100%",
  "justifyContent": "space-between"
} as const

/** `.space-selector__trigger-label` */
export const SPACE_SELECTOR_TRIGGER_LABEL = {
  "overflow": "hidden",
  "textOverflow": "ellipsis",
  "whiteSpace": "nowrap"
} as const

/** `.space-selector__chevron` */
export const SPACE_SELECTOR_CHEVRON = {
  "width": "1rem",
  "height": "1rem",
  "flexShrink": "0",
  "opacity": "0.5"
} as const

/** `.space-selector__search-icon` */
export const SPACE_SELECTOR_SEARCH_ICON = {
  "width": "1rem",
  "height": "1rem",
  "position": "absolute",
  "left": "0.5rem",
  "top": "50%",
  "transform": "translateY(-50%)",
  "opacity": "0.5"
} as const

/** `.space-selector__search-input` */
export const SPACE_SELECTOR_SEARCH_INPUT = {
  "paddingLeft": "2rem"
} as const

/** `.space-selector__empty` */
export const SPACE_SELECTOR_EMPTY = {
  "paddingVertical": "1rem",
  "paddingHorizontal": "1rem",
  "textAlign": "center",
  "display": "block"
} as const

/** `.space-selector__item-icon` */
export const SPACE_SELECTOR_ITEM_ICON = {
  "width": "1rem",
  "height": "1rem",
  "flexShrink": "0",
  "opacity": "0.6"
} as const

/** `.space-selector__new-icon` */
export const SPACE_SELECTOR_NEW_ICON = {
  "width": "1rem",
  "height": "1rem"
} as const

/** `.space-selector__create-form` */
export const SPACE_SELECTOR_CREATE_FORM = {
  "paddingVertical": "0.25rem",
  "paddingHorizontal": "0.25rem"
} as const

/** `.space-selector__create-btn` */
export const SPACE_SELECTOR_CREATE_BTN = {
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "0%"
} as const

/** `.user-detail__empty` */
export const USER_DETAIL_EMPTY = {
  "display": "flex",
  "alignItems": "center",
  "justifyContent": "center",
  "height": "100%"
} as const

/** `.user-detail__empty-avatar` */
export const USER_DETAIL_EMPTY_AVATAR = {
  "marginTop": "0",
  "marginRight": "auto",
  "marginBottom": "1rem",
  "marginLeft": "auto",
  "backgroundColor": "var(--muted)"
} as const

/** `.user-detail__empty-icon` */
export const USER_DETAIL_EMPTY_ICON = {
  "width": "1.75rem",
  "height": "1.75rem",
  "opacity": "0.5"
} as const

/** `.user-detail__empty-caption` */
export const USER_DETAIL_EMPTY_CAPTION = {
  "maxWidth": "20rem"
} as const

/** `.user-detail__panel` */
export const USER_DETAIL_PANEL = {
  "height": "100%",
  "display": "flex",
  "flexDirection": "column",
  "overflow": "hidden"
} as const

/** `.user-detail__header-row` */
export const USER_DETAIL_HEADER_ROW = {
  "display": "flex",
  "alignItems": "flex-start",
  "gap": "1rem"
} as const

/** `.user-detail__name` */
export const USER_DETAIL_NAME = {
  "overflow": "hidden",
  "textOverflow": "ellipsis",
  "whiteSpace": "nowrap"
} as const

/** `.user-detail__body` */
export const USER_DETAIL_BODY = {
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "0%",
  "overflowY": "auto",
  "paddingVertical": "1.5rem",
  "paddingHorizontal": "2rem"
} as const

/** `.user-detail__info-icon` */
export const USER_DETAIL_INFO_ICON = {
  "width": "1rem",
  "height": "1rem",
  "opacity": "0.6"
} as const

/** `.user-detail__info-card-row` */
export const USER_DETAIL_INFO_CARD_ROW = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.25rem"
} as const

/** `.user-detail__permissions-heading` */
export const USER_DETAIL_PERMISSIONS_HEADING = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.5rem",
  "marginBottom": "1rem"
} as const

/** `.user-detail__role-icon` */
export const USER_DETAIL_ROLE_ICON = {
  "width": "1.25rem",
  "height": "1.25rem",
  "flexShrink": "0"
} as const

/** `.user-detail__status-heading` */
export const USER_DETAIL_STATUS_HEADING = {
  "marginBottom": "1rem"
} as const

/** `.confirm-dialog__content` */
export const CONFIRM_DIALOG_CONTENT = {
  "paddingVertical": "1.5rem",
  "paddingHorizontal": "1.5rem",
  "textAlign": "center"
} as const

/** `.confirm-dialog__icon` */
export const CONFIRM_DIALOG_ICON = {
  "width": "1.5rem",
  "height": "1.5rem",
  "color": "var(--destructive)"
} as const

/** `.user-detail__role-check-icon` */
export const USER_DETAIL_ROLE_CHECK_ICON = {
  "width": "1rem",
  "height": "1rem"
} as const

/** `.user-detail__icon-sm` */
export const USER_DETAIL_ICON_SM = {
  "width": "1rem",
  "height": "1rem"
} as const

/** `.confirm-dialog__action-btn` */
export const CONFIRM_DIALOG_ACTION_BTN = {
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "0%"
} as const
