#!/usr/bin/env node
/**
 * Reads dist/web/ and generates src/cli/web-assets.ts with all files
 * embedded as base64 strings so bin.js is fully self-contained.
 */
import { readFileSync, readdirSync, statSync, writeFileSync, existsSync } from 'node:fs'
import { resolve, relative, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = fileURLToPath(new URL('.', import.meta.url))
const root = resolve(__dirname, '..')
const webDir = resolve(root, 'dist/web')
const outFile = resolve(root, 'src/cli/web-assets.ts')

if (!existsSync(webDir)) {
  console.error('dist/web/ not found — run pnpm build:web first')
  process.exit(1)
}

function walk(dir, base = dir) {
  const entries = readdirSync(dir, { withFileTypes: true })
  const files = {}
  for (const entry of entries) {
    const full = join(dir, entry.name)
    if (entry.isDirectory()) {
      Object.assign(files, walk(full, base))
    } else {
      const rel = relative(base, full).replace(/\\/g, '/')
      files[rel] = readFileSync(full).toString('base64')
    }
  }
  return files
}

const assets = walk(webDir)
const keys = Object.keys(assets)
console.log(`Embedding ${keys.length} web assets into src/cli/web-assets.ts`)

const lines = [
  '// Auto-generated by scripts/embed-web.mjs — do not edit manually',
  'const assets: Record<string, string> = {',
  ...keys.map(k => `  ${JSON.stringify(k)}: ${JSON.stringify(assets[k])},`),
  '}',
  'export default assets',
  '',
]

writeFileSync(outFile, lines.join('\n'))
console.log(`Written: ${outFile}`)
