/**
 * Prop bags for the former `libs/ui/src/studio/workflow/workflow-editor/tasklist-editor.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead.
 *
 * The stylesheet is GONE. The rules the sweep could not take — every one carrying a `transition:`,
 * plus the `--goal`/`--active`/`--on`/`--off` modifiers it will not resolve because the class is
 * built at runtime — were hand-migrated into the HAND-WRITTEN section at the bottom of this file.
 * Dead rules (`__manifest-body > div`, `__task-body > div:not(…)`, `__task-order` descendants — no
 * call site) were dropped. See docs/tamagui-idiomatic-migration.md §5.
 */
/** `.tasklist-editor` */
export const TASKLIST_EDITOR = {
  "display": "flex",
  "flexDirection": "column",
  "height": "100%",
  "minHeight": "0",
  "overflowY": "auto",
  "backgroundColor": "var(--color-background)"
} as const

/** `.tasklist-editor__header` */
export const TASKLIST_EDITOR_HEADER = {
  "position": "sticky",
  "top": "0",
  "zIndex": "20",
  "backgroundColor": "var(--color-card)",
  "borderBottomWidth": "1px",
  "borderBottomStyle": "solid",
  "borderBottomColor": "var(--color-border)"
} as const

/** `.tasklist-editor__header-inner` */
export const TASKLIST_EDITOR_HEADER_INNER = {
  "maxWidth": "56rem",
  "marginVertical": "0",
  "marginHorizontal": "auto",
  "width": "100%",
  "paddingVertical": "1rem",
  "paddingHorizontal": "1.5rem"
} as const

/** `.tasklist-editor__header-top` */
export const TASKLIST_EDITOR_HEADER_TOP = {
  "alignItems": "center"
} as const

/** `.tasklist-editor__header-actions` */
export const TASKLIST_EDITOR_HEADER_ACTIONS = {
  "marginLeft": "auto"
} as const

/** `.tasklist-editor__body` */
export const TASKLIST_EDITOR_BODY = {
  "maxWidth": "56rem",
  "width": "100%",
  "marginVertical": "0",
  "marginHorizontal": "auto",
  "paddingVertical": "1.5rem",
  "paddingHorizontal": "1.5rem",
  "display": "flex",
  "flexDirection": "column",
  "gap": "1.25rem"
} as const

/** `.tasklist-editor__section-divider` */
export const TASKLIST_EDITOR_SECTION_DIVIDER = {
  "height": "1px",
  "backgroundColor": "var(--color-border)",
  "marginVertical": "0.25rem",
  "marginHorizontal": "0"
} as const

/** `.tasklist-editor__empty` */
export const TASKLIST_EDITOR_EMPTY = {
  "display": "flex",
  "flexDirection": "column",
  "alignItems": "center",
  "gap": "0.75rem",
  "textAlign": "center",
  "paddingVertical": "3rem",
  "paddingHorizontal": "1.5rem",
  "backgroundColor": "var(--color-card)",
  "borderWidth": "2px",
  "borderStyle": "dashed",
  "borderColor": "var(--color-border)",
  "borderRadius": "0.75rem"
} as const

/** `.tasklist-editor__task-list` */
export const TASKLIST_EDITOR_TASK_LIST = {
  "display": "flex",
  "flexDirection": "column",
  "gap": "1rem"
} as const

/** `.tasklist-editor__manifest` */
export const TASKLIST_EDITOR_MANIFEST = {
  "backgroundColor": "var(--color-card)",
  "borderWidth": "1px",
  "borderStyle": "solid",
  "borderColor": "var(--color-border)",
  "borderRadius": "0.75rem",
  "paddingVertical": "1.25rem",
  "paddingHorizontal": "1.25rem"
} as const

/** `.tasklist-editor__manifest-header` */
export const TASKLIST_EDITOR_MANIFEST_HEADER = {
  "marginBottom": "1rem"
} as const

/** `.tasklist-editor__manifest-body` */
export const TASKLIST_EDITOR_MANIFEST_BODY = {
  "display": "flex",
  "flexDirection": "column",
  "gap": "1rem"
} as const

/** `.tasklist-editor__task-header` */
export const TASKLIST_EDITOR_TASK_HEADER = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.5rem",
  "marginBottom": "1rem"
} as const

/** `.tasklist-editor__task-order` */
export const TASKLIST_EDITOR_TASK_ORDER = {
  "display": "inline-flex",
  "alignItems": "center",
  "justifyContent": "center",
  "width": "1.5rem",
  "height": "1.5rem",
  "flexShrink": "0",
  "borderRadius": "9999px",
  "fontSize": "0.75rem",
  "fontWeight": "700",
  "backgroundColor": "var(--color-muted)",
  "color": "var(--color-muted-foreground)"
} as const

/** `.tasklist-editor__goal-badge` */
export const TASKLIST_EDITOR_GOAL_BADGE = {
  "display": "inline-flex",
  "alignItems": "center",
  "paddingVertical": "0.125rem",
  "paddingHorizontal": "0.5rem",
  "borderRadius": "9999px",
  "fontSize": "0.6875rem",
  "fontWeight": "600",
  "textTransform": "uppercase",
  "letterSpacing": "0.05em",
  "backgroundColor": "color-mix(in srgb, var(--color-primary) 15%, transparent)",
  "color": "var(--color-primary)"
} as const

/** `.tasklist-editor__task-controls` */
export const TASKLIST_EDITOR_TASK_CONTROLS = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.25rem",
  "marginLeft": "auto"
} as const

/** `.tasklist-editor__task-body` */
export const TASKLIST_EDITOR_TASK_BODY = {
  "display": "flex",
  "flexDirection": "column",
  "gap": "1rem"
} as const

/** `.tasklist-editor__depends-grid` */
export const TASKLIST_EDITOR_DEPENDS_GRID = {
  "display": "flex",
  "flexWrap": "wrap",
  "gap": "0.5rem"
} as const

/** `.tasklist-editor__flags-row` */
export const TASKLIST_EDITOR_FLAGS_ROW = {
  "display": "flex",
  "flexDirection": "row",
  "flexWrap": "wrap",
  "alignItems": "flex-end",
  "gap": "1.5rem",
  "paddingTop": "0.25rem"
} as const

/** `.tasklist-editor__flag-item` */
export const TASKLIST_EDITOR_FLAG_ITEM = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.5rem"
} as const

/** `.tasklist-editor__output-rows` */
export const TASKLIST_EDITOR_OUTPUT_ROWS = {
  "display": "flex",
  "flexDirection": "column",
  "gap": "0.5rem"
} as const

/** `.tasklist-editor__output-row` */
export const TASKLIST_EDITOR_OUTPUT_ROW = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.5rem"
} as const

// ── HAND-WRITTEN ─────────────────────────────────────────────────────────────────────────────
// Everything below was migrated by hand, not by the sweep. `transition:` has no prop form and
// stays a utility className at the call site, alongside the other ~130 `transition-*` uses.

/** `.tasklist-editor__add-task-btn` (+ `:hover`) */
export const TASKLIST_EDITOR_ADD_TASK_BTN = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  gap: '0.5rem',
  width: '100%',
  padding: '0.75rem',
  fontSize: '0.875rem',
  fontWeight: '500',
  color: 'var(--color-muted-foreground)',
  backgroundColor: 'transparent',
  borderWidth: 2,
  borderStyle: 'dashed',
  borderColor: 'var(--color-border)',
  borderRadius: '0.75rem',
  cursor: 'pointer',
  hoverStyle: { color: 'var(--color-primary)', borderColor: 'var(--color-primary)' },
} as const

/** `.tasklist-editor__task-form` (+ `:hover`) */
export const TASKLIST_EDITOR_TASK_FORM = {
  position: 'relative',
  backgroundColor: 'var(--color-card)',
  borderWidth: 1,
  borderColor: 'var(--color-border)',
  borderRadius: '0.75rem',
  padding: '1.25rem',
  hoverStyle: { borderColor: 'color-mix(in srgb, var(--color-primary) 40%, var(--color-border))' },
} as const

/** `.tasklist-editor__task-form--goal` — the box-shadow ring is a single-layer Tamagui shadow. */
export const TASKLIST_EDITOR_TASK_FORM_GOAL = {
  borderColor: 'color-mix(in srgb, var(--color-primary) 55%, transparent)',
  shadowColor: 'color-mix(in srgb, var(--color-primary) 35%, transparent)',
  shadowOffset: { width: 0, height: 0 },
  shadowRadius: 1,
} as const

/** `.tasklist-editor__depends-btn` */
export const TASKLIST_EDITOR_DEPENDS_BTN = {
  paddingVertical: '0.25rem',
  paddingHorizontal: '0.75rem',
  borderRadius: 9999,
  fontSize: '0.8125rem',
  fontWeight: '500',
  borderWidth: 1,
  borderColor: 'transparent',
  cursor: 'pointer',
} as const
/** `.tasklist-editor__depends-btn--active` */
export const TASKLIST_EDITOR_DEPENDS_BTN_ACTIVE = {
  backgroundColor: 'color-mix(in srgb, var(--color-primary) 15%, transparent)',
  color: 'var(--color-primary)',
  borderColor: 'color-mix(in srgb, var(--color-primary) 35%, transparent)',
} as const
/** `.tasklist-editor__depends-btn--inactive` (+ `:hover`) */
export const TASKLIST_EDITOR_DEPENDS_BTN_INACTIVE = {
  backgroundColor: 'var(--color-muted)',
  color: 'var(--color-muted-foreground)',
  hoverStyle: { color: 'var(--color-foreground)' },
} as const

/** `.tasklist-editor__flag-condition` */
export const TASKLIST_EDITOR_FLAG_CONDITION = {
  display: 'flex',
  flexDirection: 'column',
  gap: '0.375rem',
  flexGrow: 1,
  flexShrink: 1,
  flexBasis: '12rem',
  minWidth: '12rem',
} as const

/** `.tasklist-editor__toggle` (+ `--on` / `--off`) */
export const TASKLIST_EDITOR_TOGGLE = {
  position: 'relative',
  flexShrink: 0,
  width: '2.25rem',
  height: '1.25rem',
  padding: 0,
  borderWidth: 0,
  borderRadius: 9999,
  cursor: 'pointer',
} as const
export const TASKLIST_EDITOR_TOGGLE_ON = { backgroundColor: 'var(--color-primary)' } as const
export const TASKLIST_EDITOR_TOGGLE_OFF = { backgroundColor: 'var(--color-border)' } as const

/** `.tasklist-editor__toggle-knob` (+ `--on` / `--off`) */
export const TASKLIST_EDITOR_TOGGLE_KNOB = {
  position: 'absolute',
  top: '0.1875rem',
  left: '0.1875rem',
  width: '0.875rem',
  height: '0.875rem',
  borderRadius: 9999,
  backgroundColor: 'var(--color-card)',
} as const
export const TASKLIST_EDITOR_TOGGLE_KNOB_ON = { transform: 'translateX(1rem)' } as const
export const TASKLIST_EDITOR_TOGGLE_KNOB_OFF = { transform: 'translateX(0)' } as const

/** `.tasklist-editor__output-field-input` */
export const TASKLIST_EDITOR_OUTPUT_FIELD_INPUT = {
  flexGrow: 1, flexShrink: 1, flexBasis: 'auto', minWidth: 0,
} as const

/** `.tasklist-editor__add-output-btn` (+ `:hover`) */
export const TASKLIST_EDITOR_ADD_OUTPUT_BTN = {
  alignSelf: 'flex-start',
  paddingVertical: '0.375rem',
  paddingHorizontal: '0.75rem',
  fontSize: '0.8125rem',
  fontWeight: '500',
  color: 'var(--color-muted-foreground)',
  backgroundColor: 'transparent',
  borderWidth: 1,
  borderStyle: 'dashed',
  borderColor: 'var(--color-border)',
  borderRadius: '0.5rem',
  cursor: 'pointer',
  hoverStyle: { color: 'var(--color-primary)', borderColor: 'var(--color-primary)' },
} as const
