/**
 * Prop bags for the former `@lmthing/css/components/thing/thing-panel/index.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.thing-panel__input-form` */
export const THING_PANEL_INPUT_FORM = {
  "paddingVertical": "0.75rem",
  "paddingHorizontal": "1rem",
  "borderTopWidth": "1px",
  "borderTopStyle": "solid",
  "borderTopColor": "var(--border)",
  "display": "flex",
  "gap": "0.5rem",
  "alignItems": "flex-end"
} as const

/** `.thing-panel__textarea` */
export const THING_PANEL_TEXTAREA = {
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "0%",
  "resize": "none",
  "fontSize": "0.875rem"
} as const
