/**
 * Prop bags for the former `@lmthing/css/components/knowledge` stylesheet.
 *
 * Generated by `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4); the stylesheet
 * is deleted — all 67 rules converted. `@apply` lines went through the same map the P3 className
 * codemod uses, so the two agree by construction.
 */
/** `.create-field-inline__header-row` */
export const CREATE_FIELD_INLINE_HEADER_ROW = {
  "display": "flex",
  "justifyContent": "space-between",
  "alignItems": "center"
} as const

/** `.create-field-inline__title-row` */
export const CREATE_FIELD_INLINE_TITLE_ROW = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.75rem"
} as const

/** `.create-field-inline__icon` */
export const CREATE_FIELD_INLINE_ICON = {
  "width": "1.25rem",
  "height": "1.25rem"
} as const

/** `.create-field-inline__close-icon` */
export const CREATE_FIELD_INLINE_CLOSE_ICON = {
  "width": "1rem",
  "height": "1rem"
} as const

/** `.create-field-inline__actions` */
export const CREATE_FIELD_INLINE_ACTIONS = {
  "display": "flex"
} as const

/** `.create-field-inline__action-btn` */
export const CREATE_FIELD_INLINE_ACTION_BTN = {
  "flexGrow": 1,
  "flexShrink": 1,
  "flexBasis": "0%"
} as const

/** `.delete-modal__warning-icon` */
export const DELETE_MODAL_WARNING_ICON = {
  "width": "1.125rem",
  "height": "1.125rem",
  "color": "var(--destructive)"
} as const

/** `.delete-modal__title` */
export const DELETE_MODAL_TITLE = {
  "color": "var(--destructive)"
} as const

/** `.delete-modal__close-icon` */
export const DELETE_MODAL_CLOSE_ICON = {
  "width": "1rem",
  "height": "1rem"
} as const

/** `.delete-modal__note` */
export const DELETE_MODAL_NOTE = {
  "marginTop": "0.5rem",
  "display": "block"
} as const

/** `.dir-metadata__header` */
export const DIR_METADATA_HEADER = {
  "alignItems": "center",
  "gap": "0.75rem"
} as const

/** `.dir-metadata__icon` */
export const DIR_METADATA_ICON = {
  "width": "1.5rem",
  "height": "1.5rem",
  "color": "var(--muted-foreground)"
} as const

/** `.new-file-modal__title` */
export const NEW_FILE_MODAL_TITLE = {
  "color": "var(--success)"
} as const

/** `.new-file-modal__close-icon` */
export const NEW_FILE_MODAL_CLOSE_ICON = {
  "width": "1rem",
  "height": "1rem"
} as const

/** `.new-file-modal__fields` */
export const NEW_FILE_MODAL_FIELDS = {
  "paddingVertical": "0",
  "paddingHorizontal": "1.5rem"
} as const

/** `.new-file-modal__select` */
export const NEW_FILE_MODAL_SELECT = {
  "width": "100%"
} as const

/** `.new-file-modal__create-btn` */
export const NEW_FILE_MODAL_CREATE_BTN = {
  "backgroundColor": "var(--success)"
} as const

/** `.rename-modal__close-icon` */
export const RENAME_MODAL_CLOSE_ICON = {
  "width": "1rem",
  "height": "1rem"
} as const

/** `.rename-modal__error` */
export const RENAME_MODAL_ERROR = {
  "color": "var(--destructive)",
  "marginTop": "0.25rem",
  "display": "block"
} as const

/** `.unsaved-modal__warning-icon` */
export const UNSAVED_MODAL_WARNING_ICON = {
  "width": "1.125rem",
  "height": "1.125rem",
  "color": "var(--warning)"
} as const

/** `.unsaved-modal__close-icon` */
export const UNSAVED_MODAL_CLOSE_ICON = {
  "width": "1rem",
  "height": "1rem"
} as const

/** `.topic-editor__header` */
export const TOPIC_EDITOR_HEADER = {
  "display": "flex",
  "justifyContent": "space-between",
  "alignItems": "center"
} as const

/** `.topic-editor__header-actions` */
export const TOPIC_EDITOR_HEADER_ACTIONS = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.5rem"
} as const

/** `.topic-editor__settings-icon` */
export const TOPIC_EDITOR_SETTINGS_ICON = {
  "width": "0.875rem",
  "height": "0.875rem"
} as const

/** `.topic-editor__textarea` */
export const TOPIC_EDITOR_TEXTAREA = {
  "width": "100%",
  "height": "calc(100vh - 14rem)",
  "fontFamily": "monospace",
  "fontSize": "0.875rem",
  "lineHeight": "1.6",
  "resize": "none",
  "borderWidth": 0,
  "outline": "none",
  "paddingVertical": "1rem",
  "paddingHorizontal": "1rem",
  "borderRadius": "0"
} as const

/** `.markdown-toolbar__mode-btn` */
export const MARKDOWN_TOOLBAR_MODE_BTN = {
  "gap": "0.25rem"
} as const

/** `.markdown-toolbar__icon` */
export const MARKDOWN_TOOLBAR_ICON = {
  "width": "0.875rem",
  "height": "0.875rem"
} as const

/** `.markdown-toolbar__mode-icon` */
export const MARKDOWN_TOOLBAR_MODE_ICON = {
  "width": "0.75rem",
  "height": "0.75rem"
} as const

/** `.topic-viewer__empty` */
export const TOPIC_VIEWER_EMPTY = {
  "display": "flex",
  "flexDirection": "column",
  "alignItems": "center",
  "justifyContent": "center",
  "paddingVertical": "3rem",
  "paddingHorizontal": "3rem"
} as const

/** `.topic-viewer__empty-caption` */
export const TOPIC_VIEWER_EMPTY_CAPTION = {
  "maxWidth": "24rem",
  "textAlign": "center"
} as const

/** `.topic-viewer__header` */
export const TOPIC_VIEWER_HEADER = {
  "display": "flex",
  "justifyContent": "space-between",
  "alignItems": "center"
} as const

/** `.topic-viewer__header-actions` */
export const TOPIC_VIEWER_HEADER_ACTIONS = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.5rem"
} as const

/** `.topic-viewer__textarea` */
export const TOPIC_VIEWER_TEXTAREA = {
  "width": "100%",
  "height": "calc(100vh - 10rem)",
  "fontFamily": "monospace",
  "fontSize": "0.875rem",
  "lineHeight": "1.6",
  "resize": "none",
  "borderWidth": 0,
  "outline": "none",
  "paddingVertical": "1rem",
  "paddingHorizontal": "1rem"
} as const

