/**
 * Prop bags for the former `@lmthing/css/components/auth` stylesheet, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). The stylesheet is deleted.
 *
 * Only the GithubLogin rules survive as bags: the `.login-screen*` and `.pin-gate*` rules were
 * already dead — those two components were converted to props in an earlier sweep and only their
 * (unused) stylesheet imports remained.
 */
/** `.github-login__authenticated` */
export const GITHUB_LOGIN_AUTHENTICATED = {
  "display": "flex",
  "alignItems": "center",
  "gap": "0.5rem"
} as const

/** `.github-login__device-code-hint` */
export const GITHUB_LOGIN_DEVICE_CODE_HINT = {
  "marginTop": "0.5rem"
} as const

/** `.github-login__device-code` */
export const GITHUB_LOGIN_DEVICE_CODE = {
  "display": "block",
  "textAlign": "center",
  "letterSpacing": "0.2em",
  "fontSize": "1.5rem"
} as const

/** `.github-login__device-code-waiting` */
export const GITHUB_LOGIN_DEVICE_CODE_WAITING = {
  "marginTop": "0.75rem"
} as const

/** `.github-login__icon` */
export const GITHUB_LOGIN_ICON = {
  "width": "$5",
  "height": "$5"
} as const

