/**
 * Prop bags for the former `@lmthing/css/components/shell/index.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.settings-view__header` */
export const SETTINGS_VIEW_HEADER = {
  "display": "flex",
  "justifyContent": "space-between",
  "alignItems": "center",
  "width": "100%"
} as const

/** `.settings-view__tab-icon` */
export const SETTINGS_VIEW_TAB_ICON = {
  "width": "16px",
  "height": "16px"
} as const

/** `.settings-view__env-textarea` */
export const SETTINGS_VIEW_ENV_TEXTAREA = {
  "height": "16rem",
  "fontFamily": "monospace",
  "resize": "vertical"
} as const

/** `.settings-view__status--error` */
export const SETTINGS_VIEW_STATUS_ERROR = {
  "color": "var(--destructive)",
  "marginTop": "0.5rem"
} as const

/** `.settings-view__status--success` */
export const SETTINGS_VIEW_STATUS_SUCCESS = {
  "color": "var(--success)",
  "marginTop": "0.5rem"
} as const

/** `.settings-view__pkg-caption` */
export const SETTINGS_VIEW_PKG_CAPTION = {
  "marginBottom": "0.75rem"
} as const

/** `.settings-view__pkg-textarea` */
export const SETTINGS_VIEW_PKG_TEXTAREA = {
  "minHeight": "200px",
  "fontFamily": "monospace",
  "resize": "vertical"
} as const

/** `.studio-sidebar__home-link` */
export const STUDIO_SIDEBAR_HOME_LINK = {
  "display": "flex",
  "alignItems": "center",
  "justifyContent": "center",
  "width": "3rem",
  "height": "3rem",
  "flexShrink": "0"
} as const

/** `.studio-sidebar__section-chevron` */
export const STUDIO_SIDEBAR_SECTION_CHEVRON = {
  "width": "12px",
  "height": "12px"
} as const

/** `.studio-sidebar__item-icon--knowledge` */
export const STUDIO_SIDEBAR_ITEM_ICON_KNOWLEDGE = {
  "width": "16px",
  "height": "16px",
  "flexShrink": "0",
  "color": "var(--knowledge)"
} as const

/** `.studio-sidebar__create-btn` */
export const STUDIO_SIDEBAR_CREATE_BTN = {
  "opacity": "0.6"
} as const

/** `.studio-sidebar__create-icon` */
export const STUDIO_SIDEBAR_CREATE_ICON = {
  "width": "16px",
  "height": "16px",
  "flexShrink": "0"
} as const

/** `.studio-sidebar__collapsed-icon-inner` */
export const STUDIO_SIDEBAR_COLLAPSED_ICON_INNER = {
  "width": "20px",
  "height": "20px"
} as const

/** `.studio-sidebar__footer-icon` */
export const STUDIO_SIDEBAR_FOOTER_ICON = {
  "width": "20px",
  "height": "20px",
  "flexShrink": "0"
} as const

/** `.studio-sidebar__footer-label` */
export const STUDIO_SIDEBAR_FOOTER_LABEL = {
  "fontSize": "0.875rem",
  "fontWeight": "500"
} as const

