/**
 * bem-sweep — run the whole components-sweep pipeline for ONE stylesheet.
 *
 *   node libs/ui/scripts/bem-sweep.mjs <sheet.css> <props-dir> <callsite-glob-root>
 *
 * 1. emit the convertible rules as prop bags into `<props-dir>/props.ts`
 * 2. rewrite every static call site under `<callsite-glob-root>` to spread them
 * 3. prune bags nothing imported, and drop the stylesheet import where it is now dead
 * 4. trim the stylesheet to only its blocked rules (deleting it when none remain)
 *
 * See docs/tamagui-idiomatic-migration.md §4.
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { readdirSync, statSync } from 'node:fs'
import { join, relative, dirname } from 'node:path'
import { convertStylesheet } from './bem-to-props.mjs'

const [css, propsDir, root] = process.argv.slice(2)
if (!css || !propsDir || !root) { console.error('usage: bem-sweep <sheet.css> <props-dir> <root>'); process.exit(1) }

const tsx = []
;(function walk(d) {
  for (const n of readdirSync(d)) {
    const p = join(d, n)
    if (statSync(p).isDirectory()) walk(p)
    else if (n.endsWith('.tsx') && !n.includes('.test.') && !n.includes('.styled.')) tsx.push(p)
  }
})(root)

const { converted, blocked } = convertStylesheet(readFileSync(css, 'utf8'))
mkdirSync(propsDir, { recursive: true })
const propsFile = join(propsDir, 'props.ts')
const header = `/**
 * Prop bags for the former \`${css.replace('libs/css/src/', '@lmthing/css/')}\` rules, generated by
 * \`scripts/bem-to-props.mjs\` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
`
writeFileSync(propsFile, header + converted.map((c) =>
  `/** \`${c.selector}\` */\nexport const ${c.name} = ${JSON.stringify(c.props, null, 2)} as const\n`).join('\n'))

for (const f of tsx) {
  let rel = relative(dirname(f), propsFile).replace(/\\/g, '/').replace(/\.ts$/, '.js')
  if (!rel.startsWith('.')) rel = './' + rel
  execFileSync('node', [join(import.meta.dirname, 'bem-rewrite-callsites.mjs'), `--css=${css}`, `--module=${rel}`, f], { stdio: 'pipe' })
}

// prune bags nothing imported
const all = tsx.map((f) => readFileSync(f, 'utf8')).join('\n')
const src = readFileSync(propsFile, 'utf8')
const kept = src.split(/(?=\/\*\* `\.)/).filter((b, i) => {
  if (i === 0) return true
  const name = b.match(/export const (\w+)/)?.[1]
  return name && new RegExp(`\\b${name}\\b`).test(all)
})
writeFileSync(propsFile, kept.join(''))

// drop the now-dead stylesheet import
const spec = css.replace('libs/css/src/', '@lmthing/css/')
for (const f of tsx) {
  const s = readFileSync(f, 'utf8')
  const out = s.replace(new RegExp(`^import ['"]${spec}['"];?\\n`, 'm'), '')
  if (out !== s) writeFileSync(f, out)
}

execFileSync('node', [join(import.meta.dirname, 'bem-to-props.mjs'), '--trim', css], { stdio: 'inherit' })
console.log(`[bem-sweep] ${converted.length} converted, ${blocked.length} kept in CSS, ${kept.length - 1} bag(s) live`)
