/**
 * bem-sweep — run the whole components-sweep pipeline for ONE stylesheet.
 *
 *   node libs/ui/scripts/bem-sweep.mjs <sheet.css> <props-file.ts> <callsite-root>
 *
 * The props path is a FILE, not a directory: several stylesheets can share one component tree
 * (the four `workflow/*` sheets do), and pointing them at a shared `props.ts` made each run
 * overwrite the previous one's bags — the build then failed on missing exports.
 *
 * 1. emit the convertible rules as prop bags into `<props-dir>/props.ts`
 * 2. rewrite every static call site under `<callsite-glob-root>` to spread them
 * 3. prune bags nothing imported, and drop the stylesheet import where it is now dead
 * 4. trim the stylesheet to only its blocked rules (deleting it when none remain)
 *
 * See docs/tamagui-idiomatic-migration.md §4.
 */
import { execFileSync } from 'node:child_process'
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs'
import { readdirSync, statSync } from 'node:fs'
import { join, relative, dirname } from 'node:path'
import { convertStylesheet, trimStylesheet, serializeBag } from './bem-to-props.mjs'

const [css, propsFile, root] = process.argv.slice(2)
if (!css || !propsFile || !root) { console.error('usage: bem-sweep <sheet.css> <props-file.ts> <root>'); process.exit(1) }

const tsx = []
;(function walk(d) {
  for (const n of readdirSync(d)) {
    const p = join(d, n)
    if (statSync(p).isDirectory()) walk(p)
    else if (n.endsWith('.tsx') && !n.includes('.test.') && !n.includes('.styled.')) tsx.push(p)
  }
})(root)

// The sweep is DESTRUCTIVE and NOT idempotent: it trims the stylesheet, so a second run
// regenerates the bags from what is LEFT and drops every bag the first run already wired into
// call sites (the build then fails on missing exports). Refuse to re-run over its own output.
if (existsSync(propsFile)) {
  console.error(`${propsFile} already exists — this sheet has been swept. Re-running would drop the bags its call sites import. Revert the sheet to its pre-sweep state first.`)
  process.exit(1)
}
const { converted, blocked } = convertStylesheet(readFileSync(css, 'utf8'))
mkdirSync(dirname(propsFile), { recursive: true })
const header = `/**
 * Prop bags for the former \`${css.replace('libs/css/src/', '@lmthing/css/')}\` rules, generated by
 * \`scripts/bem-to-props.mjs\` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
`
writeFileSync(propsFile, header + converted.map((c) =>
  `/** \`${c.selector}\` */\nexport const ${c.name} = ${serializeBag(c.props)} as const\n`).join('\n'))

for (const f of tsx) {
  let rel = relative(dirname(f), propsFile).replace(/\\/g, '/').replace(/\.ts$/, '.js')
  if (!rel.startsWith('.')) rel = './' + rel
  execFileSync('node', [join(import.meta.dirname, 'bem-rewrite-callsites.mjs'), `--css=${css}`, `--module=${rel}`, f], { stdio: 'pipe' })
}

// prune bags nothing imported
const all = tsx.map((f) => readFileSync(f, 'utf8')).join('\n')
const src = readFileSync(propsFile, 'utf8')
const kept = src.split(/(?=\/\*\* `\.)/).filter((b, i) => {
  if (i === 0) return true
  const name = b.match(/export const (\w+)/)?.[1]
  return name && new RegExp(`\\b${name}\\b`).test(all)
})
writeFileSync(propsFile, kept.join(''))

// drop the now-dead stylesheet import
const spec = css.replace('libs/css/src/', '@lmthing/css/')
for (const f of tsx) {
  const s = readFileSync(f, 'utf8')
  const out = s.replace(new RegExp(`^import ['"]${spec}['"];?\\n`, 'm'), '')
  if (out !== s) writeFileSync(f, out)
}

// A converted rule may STILL be referenced after the rewrite — the rewriter only touches static
// `className="…"`, so a class used inside a template literal or `cn(...)` survives. Removing its
// rule would silently unstyle it (this bit `functions-editor__list-item--active` and
// `component-editor__list-item--active` on the first run). Keep any such rule in the stylesheet.
const after = tsx.map((f) => readFileSync(f, 'utf8')).join('\n')
const stillUsed = converted
  .map((c) => c.selector)
  .filter((sel) => new RegExp(`\\b${sel.slice(1).replace(/[-]/g, '\\-')}\\b`).test(after))
const keepInCss = [...new Set([...blocked.map((b) => b.selector), ...stillUsed])]
const rest = trimStylesheet(readFileSync(css, 'utf8'), keepInCss)
if (rest) writeFileSync(css, rest); else unlinkSync(css)
if (stillUsed.length) {
  console.log(`  kept ${stillUsed.length} converted rule(s) still referenced dynamically: ${stillUsed.join(', ')}`)
}
console.log(`[bem-sweep] ${converted.length} converted, ${keepInCss.length} kept in CSS${rest ? '' : ' → stylesheet DELETED'}, ${kept.length - 1} bag(s) live`)
