export { createSandboxSession, getQuickJSModule } from './quickjs.js';
export type { SandboxSession, SandboxConfig } from './quickjs.js';
export { BoundaryDetector } from './boundary.js';
export type { BoundaryResult } from './boundary.js';
export { analyzeCapture } from './capture.js';
export type { CaptureResult, CaptureDecision, CaptureKind } from './capture.js';
export { TraceWriter } from './trace.js';
export type { TraceEvent } from './trace.js';
export { scanFileBlocks, applyFileBlock } from './file-blocks.js';
export type { FileBlockResult, FileBlockScanResult } from './file-blocks.js';
export { injectGlobal, marshalToHost, marshalToQuickJS, injectJsxRuntime } from './host-bridge.js';
export { ModuleRegistry, createImportToRequireTransformer } from './require.js';
