/**
 * Prop bags for the former `@lmthing/css/components/setup-guide/index.css` rules, generated by
 * `scripts/bem-to-props.mjs` (docs/tamagui-idiomatic-migration.md §4). Do not hand-edit — re-run
 * the sweep instead. Rules that could not convert stay in the stylesheet.
 */
/** `.lm-setup-guide` */
export const LM_SETUP_GUIDE = {
  "borderColor": "$border",
  "backgroundColor": "$muted",
  "borderWidth": "1px",
  "borderStyle": "solid",
  "borderRadius": "0.5rem",
  "overflow": "hidden"
} as const

